lib/capybara/driver/node.rb
lib/capybara/node/element.rb
lib/capybara/selenium/node.rb
lib/capybara/spec/public/test.js
lib/capybara/spec/session/node_spec.rb
lib/capybara/spec/views/with_js.erb
spec/dsl_spec.rb
spec/rack_test_spec.rb

Implementation of item discussed in Issue #1459  -  @jferris @jonleighton @mhoran Thoughts on implementing this in your drivers for Capybara 2.5 ?

Add Node#Send keys to standardize usage across drivers

---

History.md
lib/capybara/selenium/node.rb
lib/capybara/spec/session/fill_in_spec.rb

I am developing a React application where we have some controlled inputs. This means that whenever there is an onchange event, we update some application state that ends up re-rendering the input to the DOM. In practice, when testing these fields with Capybara, we've run into issues with the `fill_in` method because of how the inputs are cleared. Running some JS to set the value to empty ended up not working for us because React would immediately clobber the input with the value stored in the application state.
Using `native.clear` to clear an input before filling it in with the desired text more accurately mimics real-world behavior. This allows us to remove a warning comment and helps Capybara work better with codebases that maintain a tight control over the DOM, such as React.js.

Use native.clear to clear inputs in Selenium::Node

---

lib/capybara.rb
lib/capybara/node/finders.rb
lib/capybara/selector.rb
lib/capybara/spec/session/first_spec.rb
lib/capybara/spec/spec_helper.rb

This adds Capybara.first_default_waiting as a setting to allow making the default behavior of Node#first be to wait for at least one element to match (same as passing minimum: 1 as an option), but returning nil if no matching elements show up rather than raising Capybara::ExpectationNotMet

add Capybara.first_default_waiting setting to control default behavior of Node#first

---

lib/capybara/node/actions.rb
lib/capybara/node/matchers.rb
lib/capybara/selector.rb
lib/capybara/spec/session/click_link_spec.rb
lib/capybara/spec/session/has_link_spec.rb

Adds regex support when searching for links with `href` filters.
Solves #1510.

can find an click links with regex href values

---

lib/capybara/helpers.rb
lib/capybara/spec/session/save_page_spec.rb

Previously, if you had Capybara.asset_host defined and tried to
`save_page` on a document without a `<head>` tag (like plain text)
`inject_asset_host` would crash trying to string-replace a `<base>`
tag onto the nonexistant `<head>`.
Since there's probably no need for it to successfully inject a
`<base>` into such documents, now it will return the original content
when there is no `<head>` present.

inject_asset_host should not raise if <head> is missing

---

lib/capybara/node/simple.rb
lib/capybara/rack_test/browser.rb
lib/capybara/spec/session/title_spec.rb
lib/capybara/spec/views/with_title.erb
spec/basic_node_spec.rb

Fixes issue with concatenation of a documents title with title elements in the documents body (embedded svg for instance) when using the rack_test driver

fix for issue #1524

---

README.md
lib/capybara/rspec.rb
spec/rspec/views_spec.rb

Capybara provides a number of helpful matchers for asserting against a
DOM structure with various selectors. RSpec's view specs focus on
asserting against specific markup; this change ensures this is easier
to do.
```ruby
RSpec.describe "todos/show.html.erb", type: :view do
it "displays the todo title" do
assign :todo, Todo.new(title: "Buy milk")
render
expect(rendered).to contain "Buy milk"
expect(rendered).to have_css("header h1", text: "Buy milk")
end
end
```

Allow RSpec view specs to leverage Capybara matchers

---

lib/capybara.rb
lib/capybara/queries/text_query.rb

This PR eliminates some Ruby :warning:s when run with `RUBYOPT="-w"`.
Similar to #599, #897.

Ruby warnings

---

lib/capybara.rb

Fixes a typo `agains` -> `against`

Fix typo in documentation

---

lib/capybara/selenium/node.rb
lib/capybara/spec/views/path.erb
spec/selenium_spec.rb

This PR is to implement`Capybara::Selenium::Node#path`. It now returns a XPath which points to the node, instead of raising `NotSupportedByDriverError`.

Implement Capybara::Selenium::Node#path

---

History.md

As of [1.0.0](https://github.com/jnicklas/capybara/blob/master/History.md#deprecated), deprecated features are I think easy to understand better section of another.

add `Deprecated` section to 2.5.0 of History [ci skip]

---

lib/capybara/session.rb
lib/capybara/spec/session/visit_spec.rb

This reimplement Session#visit usuing URI#merge.  It was initially aimed at fixing Issue #1348, but I decided that #1348 wasn't really a valid use of #visit.

Visit using merge

---

lib/capybara/node/finders.rb
lib/capybara/selector.rb
lib/capybara/spec/session/find_button_spec.rb
lib/capybara/spec/session/find_field_spec.rb
lib/capybara/spec/session/has_button_spec.rb
lib/capybara/spec/session/has_field_spec.rb

* Allowing `true`, `false`, or `:all` for all selectors with the `:disabled` option
* Adding `:skip_if` option to `Filter` to skip the filter (i.e. return `true`) if this value is passed
I added the `:skip_if` option to `Filter` because so many selectors had this `:disabled` option and adding the logic to each seemed too repetitive. If there's a preferred alternate approach or a better name than `:skip_if`, let me know.

Changing :disabled option to be tristate

---

lib/capybara/selector.rb
lib/capybara/spec/session/has_select_spec.rb
lib/capybara/spec/views/form.erb

This fixes #1579
- selected filter always allows invisible options
- options filter allows invisible options if the select
itself is invisible
- with_options filter allows invisible options if the select
itself is invisible

Adjust has_select filters to allow invisible options in some cases

---

lib/capybara/rack_test/form.rb

The `Object` class in Ruby defines an instance method named `method`
that receives a symbol a returns a `Method` object. Byebug uses this
method to grab information about the parameters of each frame in the
backtrace.
The `Capybara::RackTest::Form` class defines a method called `method`,
overriding the method mentioned above. This case could probably be
rescued in `byebug`, but since the method is just a private utility
in the class, I think it is fine to just rename it to something else
inside capybara.
While renaming it, I noticed a typo in a variable name, so I made the
renamings so that the typo is corrected too.
Reference: https://github.com/deivid-rodriguez/byebug/commit/5a634640b4dd40be98e7f8f73abff013a0a6c6e7#diff-4bfdaaf6a5014abdaeae92d370b02373

Don't redefine Object method `method`.

---

README.md

The new [`have_current_path`](https://github.com/jnicklas/capybara/pull/1567) matcher is super useful, so it'd be good to mention it in the docs.

Add documentation for have_current_path

---

README.md
lib/capybara.rb
lib/capybara/cucumber.rb
lib/capybara/rails.rb
lib/capybara/rspec.rb

I was getting a circular require warning while running the `rspec-rails` test suite. This should fix it. Also took the chance to remove some unnecessary requires in other places.

Fix circular require

---

README.md

The Selenium project has moved from code.google.com to github.com, so
this commit modifies the link to the correct wiki page.
There are a few more mentions of code.google.com where two issues are
linked, but the migration to github.com has not included the historical
issues, so those links cannot be updated. The links themselves, though,
do still continue to work.

Replace deprecated google code Selenium docs with correct GitHub docs

---

README.md

Points out specifically what RSpec configuration option is being
referred to when '`spec/features`' is being suggested as the place to
put capybara specs. Alternative instructions for Rails applications has
also been added.

Update README with more RSpec and Capybara integration information

---

lib/capybara.rb

I read the existing documentation, but I was still having trouble with a single element (I was missing the `first('a')` part), so I thought another example would help someone else.

Docs: Another example of `Capybara.string`

---

lib/capybara.rb
lib/capybara/server.rb
lib/capybara/session.rb
lib/capybara/spec/session/reset_session_spec.rb
spec/server_spec.rb

This adds Capybara.reuse_server (defaults to true).  When set to false Capybara will no create a new server on a new port for each session which allows for raising server errors in the session which caused them.  This also includes  PR #1545 which adds tracking of open requests and delays during session reset until there are no open requests.  This behavior is tested with both reuse_server = true and false

Server per session - Fix Issue #1540

---

lib/capybara/queries/current_path_query.rb

The following commit used `Addressable` to normalize path comparisons: https://github.com/jnicklas/capybara/commit/d6a824c00e8ab9e1d9c76651c729ebe866b2e14b
However, it's now causing a `NameError` exception if the addressable gem is not loaded in the project,
so we're requiring it in this specific location.
*Note:* It isn't failing in the Capybara suite because `launchy` is required in a bunch of tests files, and this gem automatically loaded addressable since it's a dependency.

Require addressable gem in CurrentPathQuery

---

History.md
lib/capybara/node/simple.rb
lib/capybara/spec/session/node_spec.rb
lib/capybara/spec/views/form.erb

#visible?, #disabled?, #checked?, #selected? should return a boolean as documented - this was not the case with the rack_test driver which was instead returning the attribute value for some of the predicates.

predicates should be boolean

---

README.md

In the README, "rspec" was misspelled as "rpsec" in one place. While I was in there, I noticed a few spots where the official "RSpec" capitalization wasn't used, so I went ahead and made those consistent as well.
Thanks for this great library! Hopefully someday I'll have a more substantive PR to contribute =]

Readme rspec typo

---

lib/capybara/node/actions.rb

This PR adds some missing documentation for the `attach_file` method, which takes an options hash but didn't previously document what parameters it accepted. Please let me know if the descriptions make sense.
This is a fix for #1659

Add documention for Capybara::Node::Actions#attach_file options hash

---

History.md
capybara.gemspec
lib/capybara/selector.rb
spec/selector_spec.rb

Move the html element selector definitions from the xpath gem into the capybara selectors and modify them so nil locators devolve into just finding element types

move xpath gem html definitions into capybara

---

.travis.yml
lib/capybara/driver/base.rb
lib/capybara/rack_test/driver.rb
lib/capybara/selenium/driver.rb
lib/capybara/session.rb
lib/capybara/spec/session/reset_session_spec.rb
lib/capybara/spec/views/with_slow_unload.erb
lib/capybara/spec/views/with_unload_alert.erb
spec/selenium_spec.rb

Make sure `#reset` for the selenium driver is synchronous and handles modals that may appear.

Selenium driver reset synchronous

---

README.md

The readme makes it look/sound like that if you're using Test::Unit (or Minitest::Spec) with Rails, there's no need to add the `teardown` method given in the non-Rails snippet. However if you don't, the session and driver state will be retained between tests, which is different to the behaviour that Rspec gets by default, and obviously breaks test isolation. This PR attempts to reduce confusion that may arise (which is what happened in my case).
Ideally, I think Test::Unit / Minitest should get this behaviour by default just like Rspec does, perhaps through the [`after_teardown`](http://docs.seattlerb.org/minitest/Minitest/Test/LifecycleHooks.html#method-i-after_teardown) callback Minitest provides?

Update Readme instructions for Test::Unit and Rails

---

README.md

The anchor links in the table of contents at http://www.rubydoc.info/github/jnicklas/capybara/master don't work, because `yard`'s auto anchors differ from the content. But GitHub's work. So I added explicit heading anchors so they should work on both sites.

Explicit README heading anchors, to work on both GitHub and RubyDoc.info

---

History.md
lib/capybara.rb
lib/capybara/rails.rb
lib/capybara/session.rb
lib/capybara/spec/session/save_and_open_screenshot_spec.rb
lib/capybara/spec/session/save_page_spec.rb
lib/capybara/spec/session/save_screenshot_spec.rb
spec/selenium_spec.rb

Deprecate save_and_open_page_path in favor of save_path.  The setting is used by save_page, save_and_open_page, save_screenshot, and save_and_open_screenshot so the name save_and_open_page_path doesn't really make sense.  The behavior is also changing when any of the mentioned methods are passed a relative path it will now be interpreted as relative to the setting of Capybara.save_path, whereas previously they were interpreted as relative to Dir.pwd

Deprecate save_and_open_page_path in favor of save_path

---

lib/capybara/selector.rb
lib/capybara/spec/session/selectors_spec.rb
lib/capybara/spec/views/form.erb

This adds a label selector that finds label by id or text, and also support a :for filter that takes either a string to match against the 'for' attribute or a field element that the label is associated with

add label selector

---

History.md
lib/capybara/node/actions.rb
lib/capybara/rack_test/node.rb
lib/capybara/selector.rb
lib/capybara/spec/session/check_spec.rb
lib/capybara/spec/session/choose_spec.rb
lib/capybara/spec/session/uncheck_spec.rb
lib/capybara/spec/views/form.erb
spec/rack_test_spec.rb

This will allow #check, #uncheck, #choose to click an associated label to toggle the checkbox/radio button state if the checkbox/radio button are not inter-actable (non-visible)

Click associated label when checkbox/radio button is hidden

---

.travis.yml
History.md
lib/capybara/selenium/driver.rb
lib/capybara/spec/session/within_frame_spec.rb
lib/capybara/spec/views/frame_child.erb
lib/capybara/spec/views/frame_parent.erb

Calling switch_to.parent_frame to return from the current frame fails if the frame has been removed from inside itself.  Reverting to our previous method of storing the frame stack and then iterating back through it solves this.

Fix Issue #1690 - within_Frame error with selenium

---

History.md
lib/capybara.rb

2.7 potential fix for Issue #1692 - Working on a better solution for 2.8

reset sessions in reverse order so sessions with active servers are reset last

---

lib/capybara/selenium/driver.rb
lib/capybara/spec/session/reset_session_spec.rb
lib/capybara/spec/views/with_unload_alert.erb

Alternate to PR #1697  -  This changes selenium-webdriver to ignore unexpected alerts (raise an error) rather than the default of dismissing them which allows us to accept the alert from before unload and therefore allow unload to continue.

default selenium to raising an error when there are unexpected alerts

---

README.md

Surrounding the `Named sessions` and `Using the sessions manually` section in `Using sessions`,
To make it easier to look for how Capybara managed sessions.

Change format session section in README.md

---

History.md
lib/capybara/session.rb
lib/capybara/spec/session/node_spec.rb

This fixes issue #1719 by making it clearer why server errors are appearing from test code.

Add explanatory cause to re-raised server errors - Issue #1719

---

History.md
lib/capybara/driver/base.rb
lib/capybara/selenium/driver.rb
lib/capybara/session.rb
lib/capybara/spec/session/within_frame_spec.rb

This changes the expected frame api for drivers from `within_frame` to `switch_to_frame` accepting either the frame elment, :parent, or :top to switch to the given frame, the parent frame, or the outermost frame.   
@jferris @mhoran @jonleighton @route  Please give your thoughts?  I'd like to make this change in Capybara 2.8, however if there are reasons this couldn't be implemented relatively quickly in any drivers I may have to reconsider.  Note this only changes the driver API not the user `within_frame` API which will continue to accept index, id/name, or an element.  Once the drivers have implemented the new method we can possibly look at improving the user facing API as discussed in Issue #1365 in a future Capybara release

new frame api for drivers

---

.travis.yml
History.md
gemfiles/Gemfile.beta-versions
gemfiles/Gemfile.rspec-34
lib/capybara/rspec/features.rb
lib/capybara/spec/spec_helper.rb
spec/rspec/features_spec.rb

RSpec 3.5 added a new config.shared_context_metadata_behavior setting - http://rspec.info/blog/2016/07/rspec-3-5-has-been-released/ .  If this is set to `:apply_to_host_groups` the background/given/given! aliases will no longer be automatically included into features.  This PR fixes that issue.

Add support for RSpec 3.5+ shared_context_metadata_behavior == :apply_to_host_groups

---

History.md
lib/capybara/node/finders.rb
lib/capybara/node/matchers.rb
lib/capybara/selector.rb
lib/capybara/spec/session/has_field_spec.rb

I have come across several use cases where the field value is not completely predictable, but always follows a pattern.  It would be nice to be able to match the field value using a regular expression.
Please let me know how to improve this PR in any way.
I could not find any direct documentation of the field selector options.  Let me know if there is documentation i should update.
This PR is based off the current master and has the same failure on travis as master.  I have expanded the tests for the new feature.

Allow the `:with` option for the field selector to accept a regular expression

---

History.md
lib/capybara.rb
lib/capybara/selector.rb
lib/capybara/spec/session/find_button_spec.rb
lib/capybara/spec/session/find_field_spec.rb
lib/capybara/spec/session/find_link_spec.rb
lib/capybara/spec/spec_helper.rb
lib/capybara/spec/views/form.erb
lib/capybara/spec/views/with_html.erb

This adds support for matching on the aria-label attribute when finding fields/links/buttons (as requested in Issue #1528).  Support for the aria-labelledby attribute is not provided.  It is easy enough to add for the case where aria-labelledby is a single value ( something like `XPath.attr(:'aria-labelledby').equals(XPath.anywhere()[XPath.string.n.is(locator)].attr(:id))` ), however aria-labelledby is specified to be a space separated list of ids which I don't believe is possible to match against in a single XPath statement (XPath 1.0 anyway)

Add support for aria-label attribute in finders - Issue #1528

---

.travis.yml
History.md
lib/capybara/node/finders.rb
lib/capybara/node/matchers.rb
lib/capybara/queries/selector_query.rb
lib/capybara/result.rb
lib/capybara/selector.rb
spec/result_spec.rb

This lazily evaluates the results from `#all` when possible.  Not sure if this is a good idea or not since it potentially delays the evaluation of visibility

Optimize Capybara::Result for use with #all[idx]

---

History.md
lib/capybara/queries/text_query.rb
lib/capybara/spec/session/assert_text.rb

Fix issue with error message when expected text is missing but contains regex special characters

Fix issue with error message when expected text is missing but contains regex special characters

---

lib/capybara/node/finders.rb
lib/capybara/queries/selector_query.rb
lib/capybara/spec/session/find_spec.rb

The :exact option only has an effect when used with selector expressions built using XPath#is - warn when used with CSS expressions or XPath strings.  Additionally, stop resolving results twice when using :smart or :prefer_exact match mode and the selector would have no difference between exact and not exact.

Warn when passing :exact option that has no effect

---

lib/capybara/queries/selector_query.rb
lib/capybara/selector.rb
lib/capybara/selector/filter_set.rb
lib/capybara/selector/selector.rb
lib/capybara/spec/session/selectors_spec.rb
lib/capybara/spec/views/form.erb

This allows for options to be passed through to the xpath/css expression builders so that filtering can be done in the original xpath/css rather than requiring more communications with the browser when possible.  It also implements the :id, :name, :placeholder filters using this feature.

Implement expression based filters for Selector

---

lib/capybara/helpers.rb
lib/capybara/node/matchers.rb
lib/capybara/queries/base_query.rb
lib/capybara/queries/text_query.rb
lib/capybara/result.rb

Move some helper methods into BaseQuery - the helpers are marked as api private so should be ok to move in a minor version release

move helpers to BaseQuery

---

README.md

It was not obvious at all where to get them. Mozilla.com forces the latest version upon users.

Linkify older Firefox releases in README

---

lib/capybara/rack_test/form.rb
spec/fixtures/capybara.csv
spec/rack_test_spec.rb

MIME::Types.type_for('xxx.csv') returns an obsolete type first, which is not how the docs describe - http://www.rubydoc.info/gems/mime-types/MIME/Types#type_for-instance_method .  According to the docs they should be in priority order with non-obsolete types before obsolete types.  This works around that issue.  - Issue #1756

Work around mime-types broken sorting on MIME::Types.type_for('xxx.csv')

---

History.md
lib/capybara/selector.rb
lib/capybara/spec/session/click_button_spec.rb
lib/capybara/spec/views/form.erb

As with links, button elements may consistent entirely of an image. In such cases, one may identify the button using the value of the descendant image's alt attribute (as a screen reader would).

Select button element by descendant image alt text

---

lib/capybara/queries/selector_query.rb
lib/capybara/selector/selector.rb
spec/selector_spec.rb

This allows for a selector to have a default visibility setting.  This means a custom selector written to find input elements of type = "hidden" won't need to specify visible: false in the options every time it's used when it would only ever make sense to use the selector if visible: false/:all/:hidden was specified.
Capybara.add_selector(:hidden_field,) do
visible :hidden
css { |s| 'input[type="hidden"]' }
end
without the visibility setting this would have to be used like
page.find(:hidden_field, visible: false)  # annoying since it can only work with visible: false/:all/:hidden
with the setting it can just be
page.find(:hidden_field)

Allow a selector to specify its default visibility setting

---

.travis.yml
lib/capybara/result.rb
lib/capybara/selector.rb
lib/capybara/selenium/driver.rb
lib/capybara/session.rb
spec/result_spec.rb

Update Travis to use /dev/urandom when installing JRuby to work around the lack of entropy in /dev/random.
Change how app exceptions are raised from tests so the cause is properly set in JRuby
Disable Capybara::Result element evaluation optimization when using JRuby due to a bug in lazy enumerator evaluation - https://github.com/jruby/jruby/issues/4212

JRuby updates

---

lib/capybara/node/actions.rb
lib/capybara/node/document.rb
lib/capybara/node/element.rb
lib/capybara/node/simple.rb
lib/capybara/spec/session/choose_spec.rb
lib/capybara/spec/session/click_link_or_button_spec.rb
lib/capybara/spec/session/click_link_spec.rb
lib/capybara/spec/session/fill_in_spec.rb

This defines the return type for node actions not otherwise defined as being the element being interacted with.  This allows for chaining some actions on elements, or checking their state, etc.
element.click.send_keys(....)
element.click.selected?

Define the return type for actions where not otherwise defined

---

History.md
lib/capybara/selenium/driver.rb

PR #1774 But checking for a specific message in the exception to limit the number of errors ignored

ignore another error while quitting selenium-webdriver

---

lib/capybara/selenium/driver.rb
lib/capybara/spec/public/test.js
lib/capybara/spec/views/with_js.erb
spec/selenium_spec_chrome.rb
spec/selenium_spec_firefox.rb
spec/selenium_spec_marionette.rb

This adds setting to the selenium driver to trigger local/sessionStorage clearing during `#reset!`

optional clearing of local/session storage for selenium driver

---

lib/capybara/queries/selector_query.rb
lib/capybara/spec/session/first_spec.rb
lib/capybara/spec/session/node_spec.rb

There is currently an issue where if you use the text option combined with visible: :hidden option in a selector the text will never match.  This fixes that

Make text option work when visible == :hidden

---

lib/capybara.rb
lib/capybara/spec/session/find_spec.rb
lib/capybara/window.rb
spec/rspec/shared_spec_matchers.rb

Ruby 2.4.0 unifies Fixnum and Bignum into Integer.
https://bugs.ruby-lang.org/issues/12005
Just modified `Fixnum` to `Integer`. As a result of that will fix `warning: constant ::Fixnum is deprecated` warning in Ruby 2.4.0+.
Thanks.

Integer Unification for Ruby 2.4.0+

---

lib/capybara/driver/base.rb
lib/capybara/selenium/driver.rb
lib/capybara/session.rb
lib/capybara/spec/session/evaluate_script_spec.rb
lib/capybara/spec/session/execute_script_spec.rb

Let `execute_script` and `evaluate_script` optionally take arguments that will get passed to the scripts as `arguments`.  Selenium supports passing elements as arguments too.

Support optional passing of arguments to execute/evaluate_script

---

History.md
lib/capybara.rb
lib/capybara/helpers.rb
lib/capybara/node/document_matchers.rb
lib/capybara/node/finders.rb
lib/capybara/node/matchers.rb
lib/capybara/queries/selector_query.rb
lib/capybara/queries/text_query.rb
lib/capybara/queries/title_query.rb
lib/capybara/spec/session/has_selector_spec.rb
lib/capybara/spec/session/has_text_spec.rb
lib/capybara/spec/session/has_title_spec.rb

This adds support for `exact_text` option on selector queries, and an 'exact' option on title and text queries.  The thought is that an `exact` option always affects the primary function of the query - so the title in title queries, text in text queries, locator in selector queries.  The `exact_text` option on selector queries can be true/false in which case it will affect the `text` option, or it can be a string which is a shortcut for passing that string as the `text` option and also passing `exact_text: true`.   
The one issue of "inconsistency" is that the text query `exact` option defaults to Capybara.exact_text, but this is documented and I don't consider it a huge issue for a user to understand - and makes more sense than it defaulting to Capybara.exact from a usability pov. …

Support easier full text matching

---

lib/capybara/node/actions.rb
lib/capybara/spec/session/fill_in_spec.rb

The required `with` option to Node#fill_in masks the ability to pass a `with` option through to the fillable_field finder used to locate the field.  This allows that with a `currently_with` option.

Add currently_with option to #fill_in

---

lib/capybara/spec/session/find_spec.rb

Behaviour was changed in https://github.com/teamcapybara/capybara/commit/b13e4d3887bfbfd9bcd765c7292554a95b52f549

Fix name of one selector spec

---

lib/capybara/node/actions.rb
lib/capybara/spec/session/attach_file_spec.rb

This changes the :style option for `attach_file` to :make_visible which takes true or a hash of style options to change.  If `true` is specified it currently applies opacity:1, display: 'block'.   Still considering how to handle errors/the changes not making the field visible, currently it warns and then raises an error about not finding the element -- probably should just raise an error about the style changes not making the element visible.

Change :style option for attach_file to :make_visible

---

lib/capybara/queries/current_path_query.rb
lib/capybara/session.rb
lib/capybara/spec/session/assert_current_path.rb
lib/capybara/spec/session/current_url_spec.rb
lib/capybara/spec/session/has_current_path_spec.rb

When we experimented moving our suite to BrowserStack, `page.current_url` was often returning nil.
Calling `have_current_path` and `page.current_path` would raise:
`NoMethodError: undefined method 'path' for nil:NilClass`, with no intelligent waiting for BrowserStack to finally return a valid url.
This PR modified to only call those methods if the parsed URI is not nil. If it's nil, @actual_path remains nil.

Do not raise path exceptions on nil current_url

---

lib/capybara/rack_test/node.rb
lib/capybara/spec/session/node_spec.rb

This updates the rack_test driver so that calling Node#click on a checkbox or radio_button can change the state of the element.

Allow Node#click to set checkboxes and radio buttons in the rack_test driver

---

lib/capybara/selenium/driver.rb
lib/capybara/session.rb
lib/capybara/spec/session/evaluate_script_spec.rb
spec/shared_selenium_session.rb

Support the return of elements in nested structures (Arrays, Hashes) from evaluate_script

support elements in evaluate_script result structures

---

README.md

Follow up to #1841 and rails/rails#28254
* Remove all references to `Test::Unit`
* Add `Capybara::Minitest::Assertions` and `require`s to all Minitest/Rails examples.

Expand Minitest related instructions on `README`

---

History.md

The markdown formatting in `History.md` is messed up.  This PR gets History.md looking awesome again.

Cleanup History.md markdown and presentation

---

lib/capybara/queries/selector_query.rb
lib/capybara/selector.rb
lib/capybara/selector/expression_filter.rb
lib/capybara/selector/filter_set.rb
lib/capybara/selector/selector.rb
spec/filter_set_spec.rb
spec/selector_spec.rb

Allow to keep expression filter definitions more modular by allowing declaration outside of the main selector expression - work in progress

Allow specification of expression filters outside the main selector expression

---

README.md

Just fixing a small typo I found while reading README

Fixing a small typo in README

---

lib/capybara/queries/selector_query.rb

There is a missing square bracket at the beginning of the description message for any selector if a class is specified, this pull request adds it.
```ruby
find('.item', text: 'content', class: 'css')
```
results in:
```
expected to find ".item" with text "content" with classes css] but there were no matches
```
and after the fix:
```
expected to find ".item" with text "content" with classes [css] but there were no matches
```

Add missing bracket to a selector's description when a class is specified

---

lib/capybara/session/config.rb

Previous warning-avoidance on similar config settings has used `attr_reader` / `attr_writer`... but here as the attributes need to be listed in the constant, it seems simplest to just remove the unwanted accessor before replacing it.

Fix Ruby warnings that appeared in 2.14.0

---

README.md
capybara.gemspec
gemfiles/Gemfile.base-versions
gemfiles/Gemfile.ruby-19
lib/capybara/rack_test/driver.rb
lib/capybara/rack_test/form.rb

[mini_mime](https://github.com/discourse/mini_mime) is a much more performant replacement for the mime-types gem.  It uses the same database as mime-types, but loads it in a much more efficient manner, improving the number of allocations, memory, and speed.  The [mail](https://github.com/mikel/mail) gem, which is a core component of Rails, has already switched to it.  See https://github.com/mikel/mail/pull/1059 for more details on the mail gem changes, as well as the some performance numbers.  Bonus is that mini_mime supports Ruby versions all the way back to 1.8.7, so there's no need for a caveat anymore.
cc @SamSaffron

Switch to mini_mime gem from mime-types

---

lib/capybara/session.rb
lib/capybara/spec/session/window/switch_to_window_spec.rb
lib/capybara/spec/session/window/within_window_spec.rb
lib/capybara/spec/views/with_windows.erb

Theres's no longer any need to prevent a user from doing
within_window(window1) do
... do something ...
within_window(window2) do
... do something in window2
end
.... do something else in window1
end
This PR loosens the restrictions to allow for this (still can't be used inside `within_frame` blocks).  The restriction stays for `switch_to_window` since it can really screw things up if used inside within's

Loosen restrictions on where `within_window` can be called from

---

lib/capybara/rspec/compound.rb
lib/capybara/rspec/matchers.rb
spec/rspec/shared_spec_matchers.rb

This makes Capybara matchers waiting behavior work as expected when compounded with and/or.  This means `expect(page).to have_text('abc').or have_text('def')` will not return "instantly" if the "def" test succeeded, rather than waiting for the timeout on "abc" before trying for "def"

Make compound rspec matchers not run sequentially

---

features/step_definitions/capybara_steps.rb
lib/capybara/queries/selector_query.rb
lib/capybara/selector.rb
lib/capybara/selector/filter_set.rb
lib/capybara/selector/selector.rb
lib/capybara/spec/session/attach_file_spec.rb
lib/capybara/spec/session/check_spec.rb
lib/capybara/spec/session/choose_spec.rb
lib/capybara/spec/session/click_button_spec.rb
lib/capybara/spec/session/click_link_or_button_spec.rb
lib/capybara/spec/session/click_link_spec.rb
lib/capybara/spec/session/fill_in_spec.rb
lib/capybara/spec/session/find_spec.rb
lib/capybara/spec/session/select_spec.rb
lib/capybara/spec/session/uncheck_spec.rb
lib/capybara/spec/session/unselect_spec.rb
spec/minitest_spec_spec.rb
spec/rspec/shared_spec_matchers.rb

This adds the visibility requirement and filters with default values to the error descriptions for selector queries.  Issue #1891

Add all condtions to selector query error messages

---

README.md
lib/capybara.rb
lib/capybara/config.rb
spec/capybara_spec.rb

Option to PR# 1896 that leaves the default outputting useful info.  Experience users can then opt to silence Puma when wanted without having to register their own server block.

Allow registered servers to receive options

---

lib/capybara/node/element.rb
spec/shared_selenium_session.rb

In the current implementation, if you inspecting stale element, Capybara will wait for `default_max_wait_time` before inspecting it.
In proposed patch, this behavior is changed to immediately return obsolete element
If you have the stale collection of element this wait is multiplied by the number of elements in the collection.

Don't wait for element during inspection

---

lib/capybara/session.rb
lib/capybara/spec/session/visit_spec.rb

`Visit` with Capybara.always_include_port == true shouldn't override an explicitly specified default port.  ie.  
visit('http://www.example.com') => should visit http://www.example.com:<server port>
but
visit('http://www.example.com:80) => should visit http://www.example.com:80

Don't override port if it's explicitly specified

---

lib/capybara/selenium/node.rb
lib/capybara/spec/public/test.js
spec/shared_selenium_session.rb

If an empty value if passed in with a clear option, it seems that the
caller's intent is for the option to be honored regardless of the value
to be set in the field.
Just passing in a blank value without options would behave as it did before.
Related to this PR/use case: https://github.com/teamcapybara/capybara/pull/1498

[fix] selenium set_text passing in empty string with options

---

lib/capybara/node/finders.rb
lib/capybara/queries/ancestor_query.rb
lib/capybara/queries/selector_query.rb
lib/capybara/queries/sibling_query.rb
lib/capybara/spec/session/select_spec.rb
lib/capybara/spec/session/unselect_spec.rb
lib/capybara/spec/session/within_spec.rb

Include details of the scoping element when find errors are raised

Include within scope in element not found/ambiguous errors

---

lib/capybara/selenium/node.rb
lib/capybara/spec/views/with_fixed_header_footer.erb
spec/selenium_spec_marionette.rb
spec/shared_selenium_session.rb

On `click` when Chrome returns with an error about another element receiving the click this will attempt to move the target element to the middle of the page so it is out from behind fixed headers/footers - and then allow the click to retry.  Unfortunately current versions of Firefox with geckodriver don't return any error in this case, they just click the wrong element and silently move on so there's nothing we can really do for that.

Attempt to move element into view when selenium doesn't correctly do it

---

lib/capybara/driver/base.rb
lib/capybara/selenium/driver.rb
lib/capybara/session.rb
lib/capybara/spec/session/evaluate_async_script_spec.rb

This provides support for `Session#evaluate_script_async` which is like `evaluate_script` however the script must call a callback function (passed as the last argument) with the value to be returned.

Support asynchronous evaluate script

---

README.md

The README contained a couple of markdown syntax errors that broke syntax highlighting on GitHub. I fixed those, then added it to the fenced code blocks that were missing it.

Fix broken README syntax highlighting and add missing

---

lib/capybara/queries/text_query.rb
lib/capybara/spec/session/assert_text.rb
lib/capybara/spec/views/with_html.erb

- Remove extra period in the invisible text details message
- Add error validation test that requires `:js` for when text is changed by `text-transform` css
- When asserting on text that is changed via css in a test that requires `:js`, the test must assert how the text exactly looks on the
page, not just in HTML
- Discrepancy between pure html and actual output on page
- In this case, the text is found using case insensitive text and including non-visible text and displays both error detail messages
- When those two error detail messages (case insensitive and non-visible) are concatenated, the error looks off because of the prepended period
- Remove the prepended period so that the error looks correct
- For example before the removal of the period, the full error for [this …

Fix non-visible text error message

---

lib/capybara/selenium/driver.rb

It is possible for selenium to throw `Selenium::WebDriver::Error::SessionNotCreatedError` when calling `Capybara::Selenium::Driver#quit`.
I have not been able to determine exactly when this error might occur, but it does appear to have something to do with `geckodriver` crashing.  In these cases Firefox has quit so it seems reasonable to swallow the error in the same way that capybara handles `Errno::ECONNREFUSED`.
The stack trace looks something like this:
```
Tried to run command without establishing a connection (Selenium::WebDriver::Error::SessionNotCreatedError)
from    0:           0x4edb3c - backtrace::backtrace::trace::hc4bd56a2f176de7e
from    1:           0x4edb72 - backtrace::capture::Backtrace::new::he3b2a15d39027c46
from    2:           0x4409a1 - …
```

Rescue SessionNotCreatedError during Capybara::Selenium::Driver#quit

---

History.md

History.md: Fix header for 2.18.0

---

lib/capybara/session/config.rb

I've encountered this warning recently in tests that only run on a CI container. It seems like a more informative error message would help folks more generally, too.

show attempted url when setting invalid app_host or default_host

---

lib/capybara/minitest.rb
lib/capybara/node/base.rb
lib/capybara/rspec/matchers.rb
lib/capybara/session.rb
lib/capybara/spec/session/node_wrapper_spec.rb

This allows libraries which wrap Capybara nodes to implement a `to_capybara_node` and work with Capybaras functionality.  I'm not fully sold on this yet, still under consideration.

Proposal: Provide a way for Capybara to work with libraries which wrap Capybara nodes

---

lib/capybara/session.rb

"Symbol" was mis-typed as "Symobl". Now it's "Symbol", like it should be.
No code changes.

Fix comment typo in `session.rb`

---

lib/capybara/helpers.rb
lib/capybara/queries/ancestor_query.rb
lib/capybara/queries/text_query.rb
lib/capybara/queries/title_query.rb
lib/capybara/rack_test/node.rb
lib/capybara/rspec/matchers.rb
lib/capybara/selenium/node.rb
lib/capybara/spec/session/ancestor_spec.rb
lib/capybara/spec/session/assert_text.rb
lib/capybara/spec/session/assert_title.rb
lib/capybara/spec/session/has_text_spec.rb
lib/capybara/spec/session/node_spec.rb
lib/capybara/spec/session/text_spec.rb
lib/capybara/spec/test_app.rb
lib/capybara/spec/views/with_html.erb

Playing with potential changes for Issue #1353

Change #text to be closer to what a browser displays

---

lib/capybara.rb
spec/capybara_spec.rb

Using the Puma rack handler ends up installing a signal trap which prevents RSpec from knowing when Ctrl-c is pressed and exiting tests.  This changes the registered puma server to use Puma::Server directly so the signal trap doesn't get installed.

Use Puma::Server directly so signal handlers aren't overridden

---

Gemfile
appveyor.yml
spec/selenium_spec_edge.rb
spec/selenium_spec_ie.rb
spec/shared_selenium_session.rb

This pull request incorporates all fixes for ability to run IE tests on CI. There are some failing tests still, but they are not related to CI configuration. I think it makes sense to work on them separately.
I'm also not sure about passing `capybara_skip: skipped_tests` to definition of browser specs. 
There is a fix for `webdrivers` gem for sorting IEDriver versions properly. I guess it's fine to have it from my github profile while the pull requests is not yet accepted.
Anyway let me know what you think!

Fix running IE tests on CI

---

lib/capybara/server.rb

We've recently had some intermittent failures in our test suite with the error 'Requests did not finish in 60 seconds'. After investigating we found that the block passed to `Timeout.timeout` that was hanging. We were unable to find out why, but re-writing the code to use a `while` loop rather than `Timeout.timeout` stopped the issue from occurring. You can [read more on the mailing list](https://groups.google.com/forum/#!topic/ruby-capybara/0Glr6Fmy_rI).
Even if the intermittent problem is only effecting us, I think this change could be justified as an improvement. Timeout is generally considered dangerous to use since the exception may interrupt the code at any point. The `Server` class is the only part of capybara that uses `Timeout.timeout`, elsewhere uses a loop similar to the …

Remove uses of `Timeout.timeout` from `Server`

---

History.md
lib/capybara.rb
lib/capybara/node/element.rb
lib/capybara/session/config.rb
lib/capybara/spec/session/node_spec.rb
lib/capybara/spec/spec_helper.rb

relative to https://github.com/teamcapybara/capybara/issues/2038

feature: add a default_set_options configuration

---

History.md
lib/capybara/node/actions.rb
lib/capybara/node/element.rb
lib/capybara/spec/session/node_spec.rb

When called on an element the script is run in the context of the element (`this` in the script is the element)

Add execute/evaluate_script as Element methods

---

.rubocop.yml
History.md
lib/capybara/selector.rb
lib/capybara/selector/filter_set.rb
lib/capybara/server.rb
lib/capybara/server/animation_disabler.rb
lib/capybara/server/middleware.rb
lib/capybara/session.rb
lib/capybara/session/config.rb
lib/capybara/spec/spec_helper.rb
lib/capybara/spec/views/with_animation.erb
spec/shared_selenium_session.rb

Provide a `Capybara.disable_animation` setting which triggers middleware insertion which attempts to disable animation on pages, via CSS/JS injection.

Allow disabling animation on pages

---

capybara.gemspec

It would be useful to have direct links to http://rubygems.org/gems/capybara/ page

Add links for rubygems page

---

README.md

Adds a SemVer compatibility badge that displays the percentage of CI runs that pass when updating `capybara` between SemVer compatible versions. Data comes from Dependabot (disclosure: I built it). I've also removed the Gemnasium badge, since it now just serves an advert for GitLab 😕.
Here's what the badge looks like:
[![SemVer](https://api.dependabot.com/badges/compatibility_score?dependency-name=capybara&package-manager=bundler&version-scheme=semver)](https://dependabot.com/compatibility-score.html?dependency-name=capybara&package-manager=bundler&version-scheme=semver)

Add SemVer compatibility badge

---

lib/capybara/driver/base.rb
lib/capybara/selenium/driver.rb
lib/capybara/spec/session/window/window_spec.rb
lib/capybara/window.rb

Also works around selenium-webdriver not currently supporting calling fullscreen with chrome and chromedriver not waiting long enough for the page state to change out of fullscreen when resetting the size.

Add Window#fullscreen and support in Selenium driver

---

.travis.yml
Rakefile
docker-compose.yml
lib/capybara/selenium/driver_specializations/chrome_driver.rb
lib/capybara/selenium/nodes/chrome_node.rb
lib/capybara/selenium/nodes/marionette_node.rb
lib/capybara/spec/session/attach_file_spec.rb
spec/selenium_spec_chrome_remote.rb
spec/selenium_spec_firefox_remote.rb
spec/shared_selenium_session.rb

This tests attach_file with remote selenium chrome and firefox.  It works around Seleniums current lack of support for file_detector/remote file upload with geckodriver/firefox, unfortunately there isn't a way to work around the lack of support for multiple file uploading with chrome when using remote.

Test file uploading with remote selenium

---

lib/capybara/selenium/driver.rb

hi, there's a bug introduced in
https://github.com/teamcapybara/capybara/commit/ada77d8b91ab1b8367af5a14e9f6e434defc3818
the problem is that selenium_webdriver has Selenium::WebDriver::VERSION constant since version 3.12.0 and the code in capybara tries to detect older versions then 3.5.0
Gem::Version.new(Selenium::WebDriver::VERSION) < Gem::Version.new('3.5.0')
In my rails app I used gem selenium_webdriver, '3.11.0' (that should be fine), but after upgrading to capybara 3.3.0 all tests start to fail.
Selenium::WebDriver::VERSION wasn't defined, so rails tried to autoload it from ./app/models/version.rb which is obviously wrong.
```
Failure/Error: raise LoadError, "Unable to autoload constant #{qualified_name}, expected #{file_path} to define it" unless from_mod.const_defined?(const_name, …
```

fix selenium driver detection

---

lib/capybara/spec/session/node_spec.rb
spec/selenium_spec_marionette.rb

Click with the control key triggers a context-click and, [in Firefox, the shift key causes it to bypass JavaScript event handling][1].
[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=692139

Avoid testing control+shift+click in Firefox

---

README.md

I think at this point in 2018, it's overwhelmingly unlikely Selenium 1.x support will be backported

Remove 'at the moment' w.r.t. Selenium RC from the README

---

features/step_definitions/capybara_steps.rb
lib/capybara/node/finders.rb
lib/capybara/queries/ancestor_query.rb
lib/capybara/queries/selector_query.rb
lib/capybara/queries/sibling_query.rb
lib/capybara/result.rb
lib/capybara/selector.rb
lib/capybara/selector/filter_set.rb
lib/capybara/selector/selector.rb
lib/capybara/spec/session/ancestor_spec.rb
lib/capybara/spec/session/attach_file_spec.rb
lib/capybara/spec/session/check_spec.rb
lib/capybara/spec/session/choose_spec.rb
lib/capybara/spec/session/click_button_spec.rb
lib/capybara/spec/session/click_link_or_button_spec.rb
lib/capybara/spec/session/click_link_spec.rb
lib/capybara/spec/session/fill_in_spec.rb
lib/capybara/spec/session/find_spec.rb
lib/capybara/spec/session/node_wrapper_spec.rb
lib/capybara/spec/session/select_spec.rb
lib/capybara/spec/session/uncheck_spec.rb
lib/capybara/spec/session/unselect_spec.rb
lib/capybara/spec/views/form.erb
spec/minitest_spec_spec.rb
spec/rspec/shared_spec_matchers.rb
spec/shared_selenium_session.rb

This attempts to make errors when matching elements are not found clearer.  Previously if doing
expect(page).to have_checked_field('My field', disabled: false)
with no matching elements the error would always be 
Unable to find visible field "My field" that is checked and not disabled
With this PR if there were no field elements with "My field" associated the error would be 
Unable to find field "My field"
If there was a field but it was non-visible the error would be
Unable to find visible field "My field"
and if there was a visible field but it was either disabled, not checked or both the error would be
Unable to find visible field "My field" that is checked and not disabled

Only include node filters in error descriptions if at least one was applied

---

lib/capybara/spec/session/check_spec.rb
lib/capybara/spec/views/form.erb

An element positioned outside of the viewable document is considered hidden, effectively making that test a duplicate of [the "should check via the label if input is hidden" test][1]. The test was originally added as part of 272a052, but if one removes the implementation change, the test still passes in Chrome and Firefox. If we cover an otherwise visible element, we can address the scenario of a visible but not-interactable element, more thoroughly validating the need for the original implementation change.
[1]: https://github.com/teamcapybara/capybara/blob/master/lib/capybara/spec/session/check_spec.rb#L177

Add test for clicking label of a blocked element

---

lib/capybara/node/element.rb
lib/capybara/node/matchers.rb
lib/capybara/spec/session/assert_selector_spec.rb
spec/dsl_spec.rb
spec/minitest_spec.rb

`refute_selector` and `refute_matches_selector` should not have been defined unless the user was using minitest.  This PR raises a warning - trying to decide whether to remove them in the next minor release, or wait to a major release as SemVer would technically require.....  Usage of them without minitest should be really low since they are the only two `refute_xxx` methods that are defined without requiring capybara/minitest so it's already pretty clear to a user they should be requiring the minitest file if they want `refute_xxx` methods.

refute_selector and refute_matches_selector only with minitest

---

lib/capybara/node/matchers.rb
lib/capybara/spec/session/element/matches_selector_spec.rb

This fixes an issue when using any `matches` matcher if the current elements query_scope is not an ancestor (ie - found using sibling, etc)

Matches matcher scope - Fix for Issue #2073

---

README.md

Since baabfa5d675a1765d572421427eb41d36472c054, Capybara requires Ruby 2.3.0 or later.

Fix required Ruby version [ci skip]

---

History.md
lib/capybara/selenium/nodes/chrome_node.rb
lib/capybara/selenium/nodes/marionette_node.rb
lib/capybara/spec/public/test.js
lib/capybara/spec/session/node_spec.rb
lib/capybara/spec/views/with_js.erb
spec/shared_selenium_session.rb

This attempts to enable HTML5 native drag and drop when using the Selenium driver.  Events fired is not complete and the order may not be 100% correct.  Needs testing and feedback from users.

Fire HTML5 drag and drop events in selenium driver

---

History.md
lib/capybara.rb
lib/capybara/node/document_matchers.rb
lib/capybara/node/matchers.rb
lib/capybara/session/config.rb
lib/capybara/session/matchers.rb
lib/capybara/spec/session/has_css_spec.rb
lib/capybara/spec/session/has_title_spec.rb
lib/capybara/spec/spec_helper.rb

All the finders wait by default for matching elements to exist, as do the predicate methods.  There's a reasonable argument that can be made that in some use cases waiting is not generally useful for the predicates.  This adds a setting that allows to default the predicate methods to non-waiting -  Still needs tests,  and a final decision on whether or not this is actually a good idea.

WIP: Add Capybara.predicates_wait setting - defaults to true

---

lib/capybara/server/animation_disabler.rb
lib/capybara/session/config.rb
spec/shared_selenium_session.rb

We use a similar disable animation feature in our test suite. I want to use the capybara version of the animation disabler but it's not quite versatile enough. This adds the ability to allowlist certain css classes.
If y'all are interested in accepting this, I'd be happy to actually fix the test here.
Thanks!

animation disabler can accept CSS as well as boolean

---

History.md
lib/capybara.rb
lib/capybara/queries/text_query.rb
lib/capybara/session/config.rb
lib/capybara/spec/session/assert_text_spec.rb
lib/capybara/spec/session/has_text_spec.rb
lib/capybara/spec/spec_helper.rb

Parameter to support old (2.18.0) normalize whitespace behaviour

Support set default value for text predicates and matchers normalize whitespace behaviour

---

History.md
lib/capybara/node/actions.rb
lib/capybara/queries/selector_query.rb
lib/capybara/selector.rb
lib/capybara/selenium/node.rb
lib/capybara/selenium/nodes/marionette_node.rb
lib/capybara/spec/session/attach_file_spec.rb
lib/capybara/spec/session/check_spec.rb
lib/capybara/spec/session/choose_spec.rb
lib/capybara/spec/session/fill_in_spec.rb
lib/capybara/spec/session/uncheck_spec.rb

Experiment to allow calling `check`/`uncheck`/`choose` to operate on the element they're called on when no locator is specified.

Allow check/uncheck/choose/attach_file/fill_in to work on element called on when no locator specified

---

lib/capybara.rb

As discuss in https://github.com/teamcapybara/capybara/pull/2094, since `capybara` doesn't support `puma` version lower than 3.8.0, raising an error in that case could help people identify this problem.

Raise error if puma version is lower than 3.8.0

---

History.md

Fix typo in History [ci skip]

---

lib/capybara/selenium/node.rb
spec/selenium_spec_chrome.rb

Fixes a regression introduced in 744e990 where `input[type=date]`, `input[type=datetime]`, and `input[type=datetime-local]` can no longer be set by `String` value.
Below is a heavily-edited version of `capybara/selenium/node.rb` to illustrate the issue.
If `#set` is called with `String` value, `#set_text` is ultimately called with a `SettableValue` value, where `#to_s` is immediately called upon it, resulting in a String value of e.g. `"#<SettableValue:0x00000000008a0138>"`, which is then subsequently entered into the date field via `#send_keys`, resulting in a garbage value in the date field.
```ruby
def set(value, **options)
case self[:type]
when 'date'
set_date(value)
end
end
def set_date(value)
value = SettableValue.new(value)
return set_text(value) unless value.dateable?
end
def …
```

Fix date and time field string entry

---

lib/capybara.rb

This fixes following warning:
```
capybara/lib/capybara.rb:396: warning: instance variable @specified_session not initialized
```

Fix ruby warning

---

lib/capybara/selector/selector.rb
spec/selector_spec.rb

If a user tries to specify an expression filter to be handled by the `css` definition in a selector an error will occur when the selector is used.  This fixes that. Workaround is to specify the expression filter explicitly

Fix CSS based default expression filters

---

.travis.yml
History.md
lib/capybara/rspec/matcher_proxies.rb
spec/rspec_spec.rb

This is a workaround to fix #2115. It reverts https://github.com/teamcapybara/capybara/commit/df010d79a5c7b3418b67e1aabd570d62036f4f29 conditionally on jruby. Also picked up the regression spec written by @twalpole.

Workaround jruby prepend issue

---

lib/capybara/node/actions.rb
lib/capybara/node/finders.rb

Hi ✋ 
Document on rubydoc macro works wrong like below
https://www.rubydoc.info/github/jnicklas/capybara/Capybara%2FNode%2FActions:check
Incorrect
correct
It seems to incorrect indent cause it.
This PR fixes document macro indentation.

Fix macro on doc

---

lib/capybara/selenium/node.rb
lib/capybara/spec/session/has_css_spec.rb

Handle case where element has gone away while building `path`

---

lib/capybara/result.rb

Hi ✋ 
I found wrong point on capybara/result doc.
This PR fix it

Fix doc on result

---

lib/capybara/node/actions.rb

Hi ✋ 
In `capybara/node/action.rb`, there is duplicated parameter about options hash, one in `Parameter` section and one is `Options 
Hash (**options)` section.
This PR remove first one with @oveload directive.

Remove needless parameter[ci skip]

---

lib/capybara/selector.rb
spec/selector_spec.rb

Fix for issue mentioned in https://groups.google.com/forum/#!topic/ruby-capybara/-RBMNqYvEuo .
When the link_or_button selector combines the link and button selectors expression_filters refers to the link_or_button selector which ends up creating incorrect attribute matchers.  This fixes it by limiting to only expected attributes.

Fix :button selector evaluating :link_or_button expression filters

---

README.md
lib/capybara.rb

Since Firefox is the default browser when using Selenium, and it's easy to get started using, it would be nice to include a headless configuration for Firefox. So that's what I've done in this PR. Now we can simply set our driver to `:selenium_firefox_headless` to use it.

Add Selenium Firefox Headless driver

---

lib/capybara.rb
lib/capybara/node/actions.rb
lib/capybara/queries/selector_query.rb
lib/capybara/selector.rb
lib/capybara/selector/selector.rb
lib/capybara/spec/session/fill_in_spec.rb
lib/capybara/spec/session/find_spec.rb
lib/capybara/spec/session/select_spec.rb

This adds a warning on failure when a locator looks to be CSS/XPath instead of what should be passed as the locator.  This is a common mistake by new users who fail to read the documentation. Currently it just detects CSS id selectors and './/', '//' as XPath starters

Support locator type checking and add a warning when locator looks to be CSS/XPath but shouldn't be

---

lib/capybara/node/base.rb
lib/capybara/rack_test/driver.rb
lib/capybara/rack_test/errors.rb
lib/capybara/rack_test/node.rb
lib/capybara/selenium/extensions/find.rb
lib/capybara/spec/session/within_spec.rb
lib/capybara/spec/views/with_scope_other.erb

Enable rack_test driver to reload nodes if stale

---

lib/capybara/selenium/driver.rb

Hello,
A while ago we were experiencing annoying intermittent test failures with "Timed out waiting for Selenium session reset"
After painstaking investigation I determined that our (Ember) application was reacting to the session being cleared and navigating the browser to our login page. 
This created a race condition where sometimes this happened *after* capybara had issued @browser.navigate.to('about:blank') but before the browser had actually gone there.
Thus the loop waiting for the page to be empty timed out because the browser was not at about:blank.
I monkey patched Capybara in our code base to add this check that we are actually at about:blank inside the loop, and navigate there again if we are not.
Since I did this, we have not encountered the problem again for 4 months.
It …

Deal with race condition when reseting between tests

---

lib/capybara/rspec/matchers.rb

`Capybara::SessionMatchers#assert_text` -> `Capybara::Node::Matchers#assert_text`
https://github.com/teamcapybara/capybara/blob/a2552e2043753b3fb05b1d4db77f72ef2699187b/lib/capybara/node/matchers.rb#L666
http://www.rubydoc.info/gems/capybara/3.15.0/Capybara/RSpecMatchers#have_text-instance_method

Fix invalid class name in `Capybara::RSpec::Matchers#have_text` doc

---

lib/capybara.rb

In versions 3.14+, this "uninitialized constant Selenium" error occurs when using the :selenium_chrome driver:
```
2.2) Failure/Error:
browser_options = ::Selenium::WebDriver::Chrome::Options.new.tap do |opts|
opts.args << '--disable-site-isolation-trials'
end
NameError:
uninitialized constant Selenium
```
I believe that this error was introduced by this commit: https://github.com/teamcapybara/capybara/commit/b28912ff9764670fe400582b18e4390048cd37a0#diff-f6aa6c79750a9a5bd39ee17f3ade2974

Fix missing constant when using :selenium_chrome

---

.travis.yml
lib/capybara/queries/selector_query.rb
lib/capybara/selector.rb
lib/capybara/selector/css.rb
lib/capybara/selector/definition.rb
lib/capybara/selector/filters/locator_filter.rb
lib/capybara/selector/selector.rb
lib/capybara/spec/session/all_spec.rb
lib/capybara/spec/session/find_spec.rb
lib/capybara/spec/session/first_spec.rb
spec/selector_spec.rb

This is part of PR #2163 - This is just splitting selector definition from configured selector instances used in queries without the multiple format support.

Split selector definition and configured selector

---

History.md

I see no such method as `excatly`. Rather, I found `exactly`.

Description was wrong

---

lib/capybara/selenium/driver.rb
spec/selenium_spec_chrome.rb

This problem was introduced in [this commit](https://github.com/teamcapybara/capybara/commit/b7b6b00665c91c31c3619c7a30aae2e447aa0d7e) (i.e. since the v3.17.0 release) and is causing `NoMethodError` exceptions in all the JS-related feature specs in an app I'm working on.
The specializations are stored in a class instance variable. However, they are accessed from the `#specialize_driver` method via `self.class`.
Previously if this method was called within an instance of a subclass of `Selenium::Driver`, then it accessed the class instance variable associated with the subclass (which is `nil` by default) and not the class instance variable associated with the `Selenium::Driver` class as intended resulting in an exception like this:
NoMethodError:
private method `select' called for …

Fix access to specializations when Selenium::Driver is subclassed

---

capybara.gemspec

I think `uglifier` is development dependency.
Because this gem requires only on https://github.com/teamcapybara/capybara/blob/master/Rakefile#L68

Reduce runtime dependency

---

lib/capybara.rb

The YARD `@example` tag (which can take an optional title) makes a generated HTML a bit more readable.
See the [YARD doc](https://www.rubydoc.info/gems/yard/file/docs/Tags.md#example).

Use `@example` YARD tag for `Capybara.string` API doc

---

lib/capybara.rb

For the default value:
https://github.com/teamcapybara/capybara/blob/2585c0ef6ad113e04e71b11ea9220f6ae8b9d978/lib/capybara.rb#L489
For the available values:
https://github.com/teamcapybara/capybara/blob/2585c0ef6ad113e04e71b11ea9220f6ae8b9d978/lib/capybara/queries/selector_query.rb#L9
See also:
https://github.com/teamcapybara/capybara/blob/2585c0ef6ad113e04e71b11ea9220f6ae8b9d978/lib/capybara/node/finders.rb#L314
https://github.com/teamcapybara/capybara/blob/2585c0ef6ad113e04e71b11ea9220f6ae8b9d978/lib/capybara/node/finders.rb#L318

Add missing `match` option to `Capybara.configure` API doc

---

lib/capybara/minitest.rb

Fix broken links on `Capybara::Minitest::Assertions` API doc

---

lib/capybara/helpers.rb

- Change plain-text references to links.
- ~~Use the YARD syntax for inline code, instead of the Markdown syntax.~~ See https://github.com/teamcapybara/capybara/pull/2198#discussion_r286291677.

Small improvements for `Capybara::Helpers` API doc

---

lib/capybara.rb

This changes plain-text references to links in the `Capybara` module as possible.
Also, this fixes incorrect references and typos.

Make links in `Capybara` module API doc

---

lib/capybara/node/actions.rb
lib/capybara/node/finders.rb

- Unify the almost same macro definitions defined both in `Capybara::Node::Actions` and `Capybara::Node::Finders`.
- ~~The new macro definition is in `Capybara::Node::Base`.~~
- ~~Please give me help if anyone knows a better place! 🙏~~
- **→Resolved. See <https://github.com/teamcapybara/capybara/pull/2199#issuecomment-495012213>.**
- Change the `+find+` word in the macro to `this method`.
- See <https://github.com/teamcapybara/capybara/pull/2190/files#r285646233>.

Improve `waiting_behavior` YARD macro

---

lib/capybara/node/actions.rb

For readability on source code and usability on [rubydoc.info](https://www.rubydoc.info/github/teamcapybara/capybara).
Summary:
- Change plain-text references to links.
- Simplify links. (e.g. `{Capybara::Node::Actions#click_button}` -> `{#click_button}`)
- Fix some typos and grammar errors.

Improve `Capybara::Node::Actions` API doc

---

lib/capybara/node/element.rb

Summary:
- Change plain-text references to links.
- Add missing descriptions.
- Fix the broken list in `#send_keys` doc.
The current doc at v3.20.2: <https://www.rubydoc.info/gems/capybara/3.20.2/Capybara/Node/Element>

Improve `Capybara::Node::Element` API doc

---

lib/capybara.rb

For the default value, see below:
https://github.com/teamcapybara/capybara/blob/101bb45ad674b1827fc43c625d8640447d0819cc/lib/capybara.rb#L490

Add missing doc of the `exact_text` option

---

lib/capybara/node/finders.rb

- Fix plain-text or broken links (references).
- Remove duplicate descriptions about method options or parameters.
- Fix a bit broken formats of text at some places.
[skip ci]
The latest doc is:
https://www.rubydoc.info/gems/capybara/3.21.0/Capybara/Node/Finders

Improve `Capybara::Node::Finders` API doc

---

lib/capybara/driver/node.rb

This fixes just `@param` types of the `#set` method. It's a small fix.
Also, this omits the `options` parameter's default value. It's explicit from the method signature.
[skip ci]

Improve `Capybara::Driver::Node#set` API doc

---

lib/capybara/session.rb

- Change plain-text references to links.
- Fix broken indentations.
- Add missing parameter descriptions.
[ci skip]
The latest doc is:
https://www.rubydoc.info/gems/capybara/3.21.0/Capybara/Session

Improve `Capybara::Session` API doc

---

lib/capybara/window.rb

- Fix invalid indentations.
- Change plain-text references to links as possible.
See the latest doc: <https://www.rubydoc.info/gems/capybara/3.21.0/Capybara/Window>
[skip ci]

Improve `Capybara::Window` API doc

---

lib/capybara/session/config.rb

- Fix invalid `@param` usage in the `#test_id=` method doc.
See <https://www.rubydoc.info/gems/capybara/3.21.0/Capybara/SessionConfig#test_id=-instance_method>.
[skip ci]

Fix `Capybara::SessionConfig` API doc

---

lib/capybara/selector.rb

- Fix invalid indentations.
- Change plain-text references to links as possible.
- Mark HTML tags as code (e.g. `<a>`) in order to avoid shown as HTML.
- Replace a non-ascii character(`—`) with a ascii character(`-`), and remove RuboCop disable comments.
- The characters are mixed in the current doc.
See the latest doc: <https://www.rubydoc.info/gems/capybara/3.21.0/Capybara/Selector>
[skip ci]

Improve `Capybara::Selector` API doc

---

.gitignore
.yardopts
Rakefile
capybara.gemspec
lib/capybara.rb
lib/capybara/selector.rb

- Specify `--markup markdown` option to YARD.
- Add and publish `.yardopts` file, instead of giving the option in `Rakefile`.
This `.yardopts` file allows to use the same options on <https://www.rubydoc.info/>.
- Rewrite the `Capybara.configure` method doc because it's broken in Markdown style. See below.
- The latest doc is [here](https://www.rubydoc.info/gems/capybara/3.21.0/Capybara#configure-class_method).
[skip ci]
In addition, I re-sort the options in alphabetical order because I think too hard to find an option in the long list.
But this big change may cause a discussion. Please give me any feedback! 
Run `bundle exec rake yard`:

Markup API doc in Markdown style

---

lib/capybara.rb
lib/capybara/selector.rb

The current docs (v3.22.0):
- [`Capybara.configure`](https://www.rubydoc.info/gems/capybara/3.22.0/Capybara#configure-class_method)
- [`Capybara::Selector`](https://www.rubydoc.info/gems/capybara/3.22.0/Capybara/Selector)

Fix `Capybara` and `Selector` docs a bit [skip ci]

---

lib/capybara/rspec/matchers.rb

Summary:
- Fix broken links.
- Use `@see` tag instead of plain text `See`.
The latest doc:
https://www.rubydoc.info/gems/capybara/3.25.0/Capybara/RSpecMatchers
[skip ci]
---

Fix doc: `Capybara::RSpecMatchers`

---

lib/capybara/minitest.rb

Current doc: <http://www.rubydoc.info/gems/capybara/3.26.0/Capybara/Minitest/Assertions>
About `@see` tag: <https://www.rubydoc.info/gems/yard/file/docs/Tags.md#see>
[skip ci]

Use `@see` tag of YARD instead of plain text "see"

---

lib/capybara/node/matchers.rb

Because the YARD option `--markup markdown` has been given since PR #2210, **4** spaces is needed for code snippet (code example) instead of 2 spaces.
For example, see <https://www.rubydoc.info/gems/capybara/3.26.0/Capybara/Node/Matchers#assert_all_of_selectors-instance_method>.
See also the [Markdown spec](https://daringfireball.net/projects/markdown/syntax#precode) below:
> To produce a code block in Markdown, simply indent every line of the block by at least 4 spaces or 1 tab.
[skip ci]

Fix code example indentations in YARD

---

lib/capybara/server.rb
spec/server_spec.rb

This fixes a problem where Capybara is trying to boot a server and throws an `Errno::EADDRINUSE` exception.
I know the test is calling a private method, however, I don't know how you would like that to be dealt with, or if it is OK.

Fix eaddrinuse

---

lib/capybara/server.rb
lib/capybara/server/middleware.rb
spec/server_spec.rb

Closes: https://github.com/teamcapybara/capybara/issues/2249
Displays more information about pending requests to developers. It can be useful to see the URI of a pending request in the test stack trace instead of following the test logs.
- Backfills tests for pending requests behavior
- Add additional information on error message

Display pending requests

---

lib/capybara/session.rb

The `ArgumentError()` syntax is wrong and generates a pretty weird error:
NoMethodError: undefined method `ArgumentError' for #<Capybara::Session>

Fix raise() syntax

---

lib/capybara/selector/definition/label.rb
lib/capybara/spec/session/selectors_spec.rb
lib/capybara/spec/views/form.erb

Handle element id being returned as empty string when non-existent in label selector

---

spec/selenium_spec_firefox.rb

This test fails for Firefox with Linux - passes fine on MacOS.  I'm not really sure what Firefox is doing around modals since different tests appear to break with every version release.

Skip accept_alert test with Firefox

---

lib/capybara/selenium/extensions/html5_drag.rb
lib/capybara/spec/public/test.js
lib/capybara/spec/session/node_spec.rb

Hey Capybara team :wave:
First of all, thanks for the amazing work that you have done so far, we use `Capybara` on our daily job and rely on it for building and testing our web applications :bow:
---
HTML5 Drag and Drop.
When using HTML5 drag and drop to drag an object onto a target, the object is always dropped in the top left corner of the window (x: 0, y: 0) instead of the previously computed position within the target.
Background: HTML5 drag and drop is currently implemented via simulating a series of HTML5 events with pre-computed values for the mouse pointer position `clientX` and `clientY`. For the last events in this series (`dragleave`, `drop`, `dragend`), the previously computed position is lost on the way. Instead of carrying it along, the events use the default options without …

Preserve clientX/clientY in HTML5 drag and drop events

---

lib/capybara/selenium/driver_specializations/chrome_driver.rb

I was getting this deprecation warning (among others) when running my tests:
```
/Users/connorshea/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/capybara-3.30.0/lib/capybara/selenium/driver_specializations/chrome_driver.rb:99: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/connorshea/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/selenium-webdriver-3.142.6/lib/selenium/webdriver/chrome/driver.rb:59: warning: The called method `execute_cdp' is defined here
```
The selenium `execute_cdp` method takes `params` as a set of keyword arguments, so `params` should be passed with a doublesplat.
That's true on [Selenium `master`](https://github.com/SeleniumHQ/selenium/blob/3f2f8fdd7ec1c518fad859d37c3087d23b830510/rb/lib/selenium/web …

Fix a Ruby 2.7 deprecation warning.

---

History.md
lib/capybara/selenium/node.rb
lib/capybara/spec/views/form.erb
spec/shared_selenium_session.rb

The slider can't be controlled so set it via JS like color inputs.

Set range inputs via JS in selenium driver

---

History.md
lib/capybara/node/element.rb
lib/capybara/node/finders.rb
lib/capybara/node/simple.rb
lib/capybara/result.rb
lib/capybara/spec/session/all_spec.rb
lib/capybara/spec/views/form.erb

When running through a list of links on a page with code like
all('#my_container a').each do |link|
link.click
expect(page).to have_text 'something'
go_back
end
it would be nice to allow the `all` results to be reloaded, otherwise the elements will be stale.  This should not be the default behavior because on dynamic pages or pages with changing sets of links between refreshes the results can be highly confusing.

Optionally allow `all` results to be reloaded when stale

---

lib/capybara/minitest/spec.rb

👋 Hello! When referencing the `Capybara::Minitest` documentation recently, I noticed that most of the methods in the `Capybara::Minitest::Expectations` module were unlisted or unsearchable due to typos.
Below is a summary of the issues with the current documentation and fixes included in this PR.
_Note: the diff is slightly easier to review with [whitespace changes hidden](https://github.com/teamcapybara/capybara/pull/2305/files?utf8=✓&diff=unified&w=1) (as the main change was simply moving the yardoc comments up above the method definitions)._
- `Capybara::Minitest::Expectations` module docs missing majority of methods (because these methods are included incorrectly included under catch-all "Top Level Namespace")
- typos in `*checked_field` method names prevented them from appearing in …

update Capybara::Minitest::Expectations documentation

---

lib/capybara/minitest.rb

Continuation of updates made in #2305 
Updates Minitest::Assertion documentation as follows:
- adds documentation for undocumented assertion methods
- adds "also known as" methods to existing method documentation
- updates `See {METHOD}` syntax to be consistent w/ rest of codebase
_before_
----------
_after_

Update Capybara::Minitest::Assertion docs

---

lib/capybara.rb
lib/capybara/queries/selector_query.rb
lib/capybara/selector/definition/button.rb
lib/capybara/selector/selector.rb
lib/capybara/session/config.rb
lib/capybara/spec/public/test.js
lib/capybara/spec/session/click_button_spec.rb
lib/capybara/spec/session/has_button_spec.rb
lib/capybara/spec/spec_helper.rb
lib/capybara/spec/views/form.erb
lib/capybara/spec/views/with_js.erb

This adds support for matching on the role=button when finding button element.
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role

Add support for ARIA button role attribute

---

README.md

Closes https://github.com/teamcapybara/capybara/issues/2322

Document workaround for "Too many files" error with WebMock

---

lib/capybara/rspec/matchers/have_text.rb
spec/rspec/shared_spec_matchers.rb

All other matchers have descriptions that begin with the word `have`, like `have title` or `have current path`, so doing stuff like `it { is_expected.to have_title("Hello World") }`
gives `is expected to have title "Hello World"`
but currently, `it { is_expected.to have_text("Hello World") }`
gives `is expected to text "Hello World"` which seems wrong.
This PR fixes that.

Fix have_text description

---

lib/capybara/registrations/servers.rb

I'm not sure what (if any) test would be appropriate for this change (I looked at the earlier batch of 2.7 deprecation changes, and nothing stood out), but I'm happy to oblige.

Fixes ruby 2.7 deprecation warning when registering webrick

---

README.md

Rspec documentation was updated recently and the old link is not working anymore. This fixes it with the current equivalent information.

Update broken link from Rspec Docs

---

lib/capybara/minitest.rb
spec/minitest_spec.rb

In our application at GitHub we were seeing a warning coming from
`assert_text` on the latest version and building the source from master.
Warning we were seeing:
```
/vendor/gems/2.7.1/ruby/2.7.0/gems/capybara-3.32.2/lib/capybara/minitest.rb:56: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/vendor/gems/2.7.1/ruby/2.7.0/gems/capybara-3.32.2/lib/capybara/minitest.rb:56:in `assert_text'
```
The warning is only visible when `assert_text` is delegated from
minitest which is why I've updated the minitest_spec.rb file to include
an argument. I was unable to see or reproduce this warning in the assert
text test.
I don't really get why `ruby2_keywords` wasn't adequate for this change
but from my testing my changes work in Ruby 2.6 and …

Fix Ruby 2.7 warning in minitest assert_text

---

lib/capybara/rack_test/browser.rb
lib/capybara/spec/session/current_url_spec.rb
lib/capybara/spec/test_app.rb

Maintain URI fragment when redirecting in the rack test driver

---

lib/capybara/server/middleware.rb

When writing a new Rails system test I ran into an issue where the
browser would hang and not close, eventually failing the test due to
pending requests. There were no clear pending requests and the requests
mentioned were AJAX calls that should have been made several pages ago.
I believe the cause is an AJAX call being cancelled almost immediately
after it was initiated, but I'm not 100% positive.
Code wise, it looks like the value of `env['REQUEST_URI']` that
increments the counter is different from the `env['REQUEST_URI']` that's
decremented in the `ensure` block. This prevents the original request uri
value from being removed from the pending requests and causes the
browser to hang.
This resolves the issue by storing the `env['REQUEST_URI']` value in a
variable so it will be …

Fix middleware request uri race condition

---

lib/capybara/selenium/driver.rb

This change switches a check against the version
of `selenium-webdriver` to use the version number
defined by the library itself instead of accessing
it via `Gem.loaded_version`, as the latter relies
on the gem being loaded via RubyGems a particular
way that we happen to not be using at in the
Github monolith :)
Co-authored-by: Natasha Umer <natashau@github.com>
Co-authored-by: John Crepezzi <seejohnrun@github.com>

use Selenium::WebDriver::VERSION vs. Gem.loaded_v

---

.rubocop.yml
lib/capybara/config.rb
lib/capybara/helpers.rb
lib/capybara/node/matchers.rb
lib/capybara/registration_container.rb
lib/capybara/rspec/matchers.rb
lib/capybara/selector/definition/css.rb
lib/capybara/selector/filter_set.rb
lib/capybara/spec/session/has_css_spec.rb
lib/capybara/spec/session/matches_style_spec.rb

Follow https://github.com/teamcapybara/capybara/issues/2371.
This PR adds `uplelvel` to deprecation warning of Capybara.
The `uplevel` option has been introduced from Ruby 2.6.
> If the `uplevel` keyword argument is given, the string will be prepended with information for the given caller frame in the same format used by the `rb_warn` C function.
https://ruby-doc.org/core-2.6.0/Kernel.html#method-i-warn
On the other hand, Capybara supports Ruby 2.5.
Therefore, This PR adds `Capybara::Helpers.warn` internal method for emulating `warn 'message', uplevel: 1` in Ruby 2.5 or lower.
This option will clarify where deprecation warnings should be fixed.
```console
DEPRECATED: Calling 'has_key?' on the drivers/servers container is
deprecated without replacement
```
```console …
```

Add uplelvel to deprecation warning of Capybara

---

.travis.yml

This PR updates the CI matrix to use latest JRuby, **9.2.13.0**.
[JRuby 9.2.13.0 release blog post](https://www.jruby.org/2020/08/03/jruby-9-2-13-0.html)

CI: Use jruby-9.2.13.0

---

lib/capybara/selector/definition/button.rb
lib/capybara/selector/selector.rb
lib/capybara/spec/session/has_button_spec.rb
lib/capybara/spec/views/form.erb

Browsers consider [<button> elements][mdn-button] as
["labelable"][labelable], meaning that a `<button
id="button-with-label">` element can be labelled by a [`<label
for="button-with-label">` element][mdn-label].
This commit extends the button selector to resolve `<button>` elements
with a locator that references a `<label>` element's text. That
`<label>` element can either reference the button through its `[for]`
attribute, or it can be an ancestor of the `<button>` element.
[labelable]: https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Form_labelable
[mdn-button]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
[mdn-label]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

Find <button> elements through <label>

---

lib/capybara/server/animation_disabler.rb
lib/capybara/spec/views/with_animation.erb
spec/shared_selenium_session.rb

I have some test cases where I need to call `page.execute_script('window.scrollTo(0, 0)')` before taking a screenshot. I'm using [Tabler](https://tabler.io/), which [sets `scroll-behavior: smooth;`](https://github.com/tabler/tabler/blob/542e3541c18ccbb7d26265fd70b9357f4f4e23ea/scss/layout/_core.scss#L4), so any scroll actions are smoothly animated. This is nice in production, but annoying during tests.
This proposed change will cause the scroll to always complete instantly without any animations. (This will only work when using the default `selector_for` value of `'*'`, so that the rule matches the `html` element.)
[`scroll-behavior: auto` is the default value](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior), so I don't think this change should cause any problems.
I've …

Add "scroll-behavior: auto" CSS to Capybara::Server::AnimationDisabler

---

lib/capybara/selector/definition.rb
lib/capybara/session/matchers.rb
lib/capybara/window.rb

Changes the documentation for the `width` and `height` arguments for `Window#resize_to` to specify that Integers are expected. Also fixes a couple miscellaneous typos.

Fix various comment typos

---

lib/capybara/registrations/servers.rb
lib/capybara/spec/session/find_spec.rb
lib/capybara/spec/spec_helper.rb
spec/server_spec.rb

Hello,
I just saw a deprecation warning when running Puma 5.0.3 in Ruby 2.7: `warning: deprecated Object#=~ is called on Proc`. I initially raised the issue on the puma repo: https://github.com/puma/puma/issues/2455
But it turns out that this was a bug in Capybara: https://github.com/puma/puma/issues/2455#issuecomment-716724207
Capybara was not calling `#finalize_values` to convert default Proc into a string. I've also tried to add a test to confirm that this is fixed, but not sure if it's the best way to test this.

Call conf.clamp for puma options to convert the default :environment Proc into a String

---

History.md
lib/capybara/driver/base.rb
lib/capybara/selenium/driver.rb
lib/capybara/session.rb
spec/rack_test_spec.rb
spec/shared_selenium_session.rb

When covering hotkeys and tab-navigation with test coverage, sending
keys via particular elements (via `Node#send_keys`) can be tedious.
As an alternative, invoke `Session#send_keys` to delegate to the element
with current focus. In most (all?) browsers, `document.activeElement`
will return the `<body>` element when there are no elements with focus.
In Selenium-enabled environments, `Session#send_keys` delegates to the
current element with focus (via [document.activeElement][]). Treat
`Session#send_keys` as a no-operation in Rack Test environments.
[document.activeElement]: https://developer.mozilla.org/en-US/docs/Web/API/DocumentOrShadowRoot/activeElement

Declare `Session#send_keys`

---

lib/capybara/node/element.rb
lib/capybara/spec/session/node_spec.rb

[Capybara Test Helpers]: https://github.com/ElMassimo/capybara_test_helpers
[tests]: https://github.com/ElMassimo/capybara_test_helpers/blame/master/spec/capybara/node_spec.rb#L595-L625
[pathname was being used]: https://github.com/ElMassimo/capybara_test_helpers/blame/master/test_helpers/js_page_test_helper.rb#L41-L44
[patch]: https://github.com/ElMassimo/capybara_test_helpers/blame/master/spec/support/capybara_patches.rb#L3-L10
This pull request fixes an accidental early return in `Capybara::Node::Element#drop`.
Using `return` inside a block does not cause the block to return, it halts the execution of the current method instead. This is a very common gotcha in Ruby.
The code intended to cast `Pathname` and similar objects to a `String` path, but instead it was not performing the …

Fix bug in Capybara::Node::Element#drop causing Pathname drops to be ignored

---

History.md

The smallest typo fix in the changelog.

History.md: fix typo [ci skip]

---

History.md
lib/capybara/selenium/driver.rb

Under some random conditions, Selenium throws `Selenium::WebDriver::Error::InvalidSessionIdError` during `quit`, causing the test suite to report a failing status code.
> Finished in 1 minute 52.93 seconds (files took 3.23 seconds to load)
> 120 examples, 0 failures, 25 pending
> 
> Randomized with seed 54517
> 
> Traceback (most recent call last):
> 	11: from /usr/local/bundle/gems/capybara-3.34.0/lib/capybara/selenium/driver.rb:486:in `block in setup_exit_handler'
> 	10: from /usr/local/bundle/gems/capybara-3.34.0/lib/capybara/selenium/driver.rb:267:in `quit'
> 	 9: from /usr/local/bundle/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:168:in `quit'
> 	 8: from /usr/local/bundle/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/remote/w3c/bridge.rb:155:in …

Fix failure during quit caused by Selenium raising `InvalidSessionIdError`

---

lib/capybara/server/animation_disabler.rb
lib/capybara/spec/views/with_jquery_animation.erb
spec/shared_selenium_session.rb

Animation disabler now can only turn off the animation come from jQuery if jQuery is loaded in head, because `insert_disable` place the template at the end of head.
https://github.com/teamcapybara/capybara/blob/a08e0477ac2cfd3319d8a423d8661b73103acbf3/lib/capybara/server/animation_disabler.rb#L42-L44
If jQuery is loaded with the body, jQuery will be undefined in head so the function won't work.
https://github.com/teamcapybara/capybara/blob/a08e0477ac2cfd3319d8a423d8661b73103acbf3/lib/capybara/server/animation_disabler.rb#L46-L49
By placing it to the end of the body, developer do not have to worry about where they are loading jQuery and give a better experience 😄

Fix js animation not disable if load jquery in body

---

lib/capybara/registrations/drivers.rb

Hey! 
It seems, that 0ad261ad0a9771d2f3ee45555c34caf7e79c563e accidentally changed browser from `chrome` to `firefox` in `:selenium_chrome` and `:selenium_chrome_headless` drivers

Use chrome browser in chrome drivers

---

lib/capybara/node/actions.rb

Removed duplicate backquotes in error messages thrown by `Capybara::Node::Actions#attach_file`.

delete duplicated back quote

---

capybara.gemspec

It was recently removed from the default gems:
- https://bugs.ruby-lang.org/issues/17873
- https://github.com/ruby/ruby/pull/4530

Add matrix as a dependency for Ruby 3.1 compatibility

---

lib/capybara/node/finders.rb

There was a typo on Finders' documentation where `element` was spelled `elment`.

Update finders.rb documentation

---

History.md
lib/capybara/driver/base.rb
lib/capybara/selenium/driver.rb
lib/capybara/session.rb
lib/capybara/spec/session/active_element_spec.rb
spec/rack_test_spec.rb

As a [follow-up][] to [#2422][], expose the [document.activeElement][]
(that is, the element with focus) via the `Session`.
When called from Rack Test environments, `Session#active_element` raises
an error.
[Document.activeElement]: https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement
[follow-up]: https://github.com/teamcapybara/capybara/pull/2422#discussion_r520646573
[#2422]: https://github.com/teamcapybara/capybara/pull/2422
[document.activeElement]: https://developer.mozilla.org/en-US/docs/Web/API/Document/activeElement

Support `Session#active_element`

---

History.md
lib/capybara/queries/selector_query.rb
lib/capybara/selector.rb
lib/capybara/spec/session/active_element_spec.rb
lib/capybara/spec/session/has_button_spec.rb
lib/capybara/spec/session/has_field_spec.rb
lib/capybara/spec/session/has_link_spec.rb
lib/capybara/spec/views/form.erb
lib/capybara/spec/views/with_html.erb
spec/rack_test_spec.rb
spec/shared_selenium_session.rb

[Follow-up to #2489][], adds support for filtering fields, links, and
buttons based on whether or not they're focused.
[Follow-up to #2489]: https://github.com/teamcapybara/capybara/pull/2489

Add support for `focused:` filter

---

lib/capybara/node/actions.rb

React 17 makes some [changes to how they handle event delegation](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#changes-to-event-delegation).
One result of these changes is that:
> If you add manual DOM listeners with `document.addEventListener(...)`, you might expect them to catch all React events. In React 16 and earlier, even if you call e.stopPropagation() in a React event handler, your custom document listeners would still receive them because the native event is already at the document level. With React 17, the propagation would stop (as requested!), so your document handlers would not fire
(see: https://reactjs.org/blog/2020/08/10/react-v17-rc.html#fixing-potential-issues)
This is an issue with Capybara since `attach_file` (when used with a block) executes the following …

Fix incompatibility with React 17 when using attach_file

---

lib/capybara/server/animation_disabler.rb
spec/shared_selenium_session.rb

While I was experimenting with the [W3C rspec validations](https://github.com/Goltergaul/w3c_rspec_validators) gem, it reported all pages had invalid HTML due to the contents added by Capybara's AnimationDisabler. The W3C Validator was reporting an error:
> Element style not allowed as child of element body in this context.
>
> Contexts in which element style may be used:
>    * Where metadata content is expected.
>    * In a noscript element that is a child of a head element.
>
> Content model for element body:
>    * Flow content.
It looks like [there can't be any style tags inside the body element](https://html.spec.whatwg.org/multipage/semantics.html#the-style-element).
The `<script>` part of the markup template remains at the end of the `<body>` element because it only makes sense if …

Fix invalid HTML generated by AnimationDisabler

---

lib/capybara.rb

I needed this option recently but didn't find it on the docs. I saw it was mentioned on `lib/capybara/session/config.rb`, but that's a less obvious location.
The description includes the detail of why you would want to change this, typically to `"0.0.0.0"`, as it strikes me as the most obvious use case. Thoughts?

Document `server_host` option

---

lib/capybara/selenium/driver.rb

This PR fixes the following warning when running with selenium-webdriver 4.1.0.
```
WARN Selenium [DEPRECATION] [:browser_options] :options as a parameter for driver initialization is deprecated. Use :capabilities with an Array of value capabilities/options if necessary instead.
```

Allow selenium-webdriver 4.1.0 or higher

---

lib/capybara/rack_test/browser.rb
spec/rack_test_spec.rb

We discovered that if the RackTest browser has a current_url that
includes a fragment, then when a request is made that includes
current_url as a referrer (eg clicking a link, submitting a form) then
it will include the fragment. Accordng to the HTTP spec this is not
allowed:
user agent MUST NOT include the fragment and userinfo components of the
URI reference [RFC3986], if any, when generating the Referer field value.
See: https://httpwg.org/specs/rfc7231.html#header.referer
This seems to have been introduced when support for including the
fragment in #current_url was added in 1a48bc77162fff4484c1ded72d8e700b06e9a95a
Co-authored-by: Thao Vo <thao.vo@futurelearn.com>
We weren't sure about the right way to test this, but the test we wrote failed before and passes now.

Fix bug with fragments in referer headers in RackTest

---

lib/capybara/selenium/node.rb

Partially "fixes" #2521 
Attempted to document in RubyDocs the behaviour of the text rapid set mode. I possibly do not have the correct terminology here, so suggestions welcomed.

Document the text "rapid" mode in Capybara::Selenium::Node

---

lib/capybara/rack_test/form.rb
lib/capybara/spec/session/fill_in_spec.rb

According to [the HTML spec](https://www.w3.org/TR/html4/interact/forms.html#h-17.13.4.1) line breaks in forms should be represented as CR+LF (`\r\n`). The rack-test driver correctly converts this when a textarea contains `\n`. However if the textarea already had `\r\n` the driver adds another `\r` after the form is submitted resulting in an additional carriage return: `\r\r\n`.
This change does not add an additional carriage return when there already is one.

Rack-test driver adds additional carriage return to CR+LF in textareas

---

README.md

Very minor point...happy to have it ignored.
These tests look a lot like they are testing a Rails app, but `User.make` is not standard Rails and just felt a little out of place to me. I looked back over the README's history and issues, discussion etc. and couldn't see that it was a conscious decision _not_ to make it look like Rails. So figured it might be less confusing to newbies to have it look like familiar Rails code.

Use #create not #make in README example

---

lib/capybara/session.rb
lib/capybara/spec/session/reset_session_spec.rb
lib/capybara/spec/test_app.rb
spec/rspec_spec.rb

Otherwise they persist between RSpec tests.
Fix #2562

Reset @scopes when session is reset

---

lib/capybara/server/middleware.rb
spec/counter_spec.rb

In some cases, we get an issue when a request is not finished for Capybara, but in reality, it's finished. It looks like we have a case when URI was changed because of server redirection or something like this and the `Counter#decrement` method is going to use a fallback `@value.length`. In the original PR the `- 1` was missed, so for value `['/example']` removing of `@value.length` will resolve to `@value.delete_at(1)` instead of `@value.delete_at(0)`.
Fix fallback for Middleware::Counter#decrement which sometimes resolves to `Requests did not finish in 60 seconds` error.
https://github.com/teamcapybara/capybara/pull/2250#discussion_r326843512

Fix wrong counter behavior with changed uri

---

lib/capybara/queries/selector_query.rb
lib/capybara/spec/session/has_button_spec.rb
lib/capybara/spec/session/has_link_spec.rb
lib/capybara/spec/session/has_select_spec.rb

This PR eliminates the duplication of options proposed in the `have_xxxx` method's invalid option error message.
If the following code is executed:
```ruby
expect(page).to have_link(invalid: true)
```
The following error message appears (e.g. :href is displayed in duplicate)
```
Failure/Error: expect(page).to have_link(invalid: true)
ArgumentError:
Invalid option(s) :invalid, should be one of :above, :below, :left_of, :right_of, :near, :count, :minimum, :maximum, :between, :text, :id, :class, :style, :visible, :obscured, :exact, :exact_text, :normalize_ws, :match, :wait, :filter_set, :focused, :href, :href, :alt, :title, :download
```

Fix a duplicate options suggested in `have_xxxx` method at invalid option error message

---

lib/capybara.rb
lib/capybara/node/base.rb
lib/capybara/session/config.rb
lib/capybara/spec/spec_helper.rb
spec/capybara_spec.rb
spec/per_session_config_spec.rb

Introduce `Capybara.default_retry_interval` which customize the sleep time in `Capybara::Node::Base#synchronize` in order to save CPU usage. (#2574)

Make retry interval configurable

---

.rubocop.yml
lib/capybara/spec/session/current_scope_spec.rb
spec/minitest_spec.rb
spec/selector_spec.rb

This PR is fixed offense and obsolete warnings in rubocop.
Fixed the following obsolete warnings that occurred when running the latest version of RuboCop.
```
Warning: obsolete parameter `IgnoredMethods` (for `Metrics/BlockLength`) found in .rubocop.yml
`IgnoredMethods` has been renamed to `AllowedMethods` and/or `AllowedPatterns`.
```
The following offenses were then corrected
```
Offenses:
lib/capybara/spec/session/assert_all_of_selectors_spec.rb:8:3: C: RSpec/NoExpectationExample: No expectation found in this example.
it 'should be true if the given selectors are on the page' do ...
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/capybara/spec/session/assert_all_of_selectors_spec.rb:49:5: C: RSpec/NoExpectationExample: No expectation found in this example.
it 'should …
```

Fix offense and obsolete warnings in rubocop

---

lib/capybara/registrations/servers.rb

This is a WIP -- waiting to see what other changes are made to Puma

Update puma registration for latest master

---

CONTRIBUTING.md

This should make it easier for new contributors to get started... I spent quite a while trying to figure out how to run a single new test before eventually finding [the answer](https://groups.google.com/g/ruby-capybara/c/7ACASr4wpMI/m/7xqhD9r9GAAJ) on the mailing list.
This documents an old change... https://github.com/teamcapybara/capybara/commit/7155323929c94d981f80deff0200a062dbcdcac8

Add `:focus_` usage to contributing guidelines

---

lib/capybara/selenium/nodes/firefox_node.rb

When using CI systems, this auto-converts into a link. But appends the `.` at the end. So I've just removed it.

Update minor text/link issue in warning for FirefoxNode

---

lib/capybara/selenium/node.rb
lib/capybara/spec/test_app.rb
spec/rack_test_spec.rb
spec/selenium_spec_chrome.rb
spec/selenium_spec_firefox.rb
spec/spec_helper.rb

This pull request depends on #2613.
The two additional commits make the Firefox Selenium specs pass with the base dependency versions, making the following pass:
```bash
BUNDLE_GEMFILE='gemfiles/Gemfile.base-versions' bundle exec rake spec_firefox
```

Fix Selenium specs with base versions

---

.rubocop.yml

This PR improve a format for .rubocop.yml.
- Update the URL of the link.
- Sort alphabetically.
- Add comments for each department.
- Change comment-use text that was written as YAML to comments.

Improve a format for .rubocop.yml

---

spec/shared_selenium_session.rb

This makes specs for Chrome pass with the base dependency versions:
```
BUNDLE_GEMFILE='gemfiles/Gemfile.base-versions' bundle exec rake spec_chrome
```

Skip shadow root related spec for #evaluate_script on older Selenium

---

lib/capybara/selenium/extensions/html5_drag.rb
lib/capybara/spec/public/test.js
lib/capybara/spec/session/node_spec.rb

Fire a `dragenter` event before the two `dragover` events.
The [spec](https://www.w3.org/html/wg/spec/dnd.html#introduction-6) requires a `dragenter` event to be fired first:
> To accept a drop, the drop target has to listen to at least three events. First, the [dragenter](https://www.w3.org/html/wg/spec/dnd.html#event-dragenter) event, which is used to determine whether or not the drop target is to accept the drop.
Addresses #2576 
This is my first code contribution and I'm much more comfortable in Ruby than JavaScript so please let me know if I've done this badly or misunderstood the JavaScript side of things!
P.S. This is basically a duplicate of #2601 but rebased against latest master. I accidentally closed the other PR by deleting my branch before it had been merged. Hacktoberfest is …

Add `dragenter` event and test to `drag_to`

---

lib/capybara/server/animation_disabler.rb

Removes warning: `capybara-3.38.0/lib/capybara/server/animation_disabler.rb:21: warning: too many arguments for format string`

Cleanup animation disabler, remove deprecation warn

---

capybara.gemspec

Explicitly add test files to the gem package, with a note to explain why this is. This should deter pull request proposals to remove tests. 😂 
Hopefully, this is a quality-of-life improvement for you @twalpole.

Note why test files are included in the gem

---

.github/workflows/build.yml
gemfiles/Gemfile.rack3
lib/capybara/registrations/servers.rb
spec/rack_test_spec.rb

Experimental Rack 3 support

---

lib/capybara/selenium/nodes/edge_node.rb
spec/selenium_spec_edge.rb

This changeset introduces no changes to existing desired behavior.
This limited changeset has 3 specific changes related only to issues with Microsoft Edge browser support:
1.  Addresses an issue when using the click functionality with Microsoft Edge browser with Ruby 3.  Specifically, when using Ruby 3 and attempting to click, the following exception (and abridged stack trace is produced)
```ruby
ArgumentError:
wrong number of arguments (given 2, expected 0..1)
...
```
2. Updates the official Selenium Edge browser naming conventions from `EdgeChrome`/`edge_chrome` to `Edge`/`edge` per Selenium commit [0b23bfe](https://github.com/SeleniumHQ/selenium/commit/0b23bfe15bcf71375a29c789999c1d9e770c8f30).  This change results in now being able to successful run the `spec_edge` rake task without …

Fix MS Edge Click (Button) to Support Ruby 3 Separation of Positional and Keyword Arguments

---

History.md
lib/capybara/node/finders.rb
lib/capybara/selector/definition/link.rb
lib/capybara/spec/session/click_link_spec.rb
lib/capybara/spec/session/find_link_spec.rb
lib/capybara/spec/session/has_link_spec.rb
lib/capybara/spec/views/with_html.erb

This PR add support `:target` filter option on `:link` selector.
When wanting to write a test that checks whether the [HTML < a > target attribute](https://www.w3schools.com/tags/att_a_target.asp) has been set to `_blank` or not, it is currently not possible to use matchers like `has_link?`. If passing it as an option raises an invalid option error.
```
Failures:
1) something something test
Failure/Error: expect(page).to have_link(target: '_blank')
ArgumentError:
Invalid option(s) :target, should be one of :above, :below, :left_of, :right_of, :near, :count, :minimum, :maximum, :between, :text, :id, :class, :style, :visible, :obscured, :exact, :exact_text, :normalize_ws, :match, :wait, :filter_set, :focused, :href, :alt, :title, :download
```
Therefore, we would like to support filtering …

Add support `:target` filter option on `:link` selector

---

spec/rspec/shared_spec_matchers.rb
spec/selector_spec.rb

This PR is fix warnings when running RuboCop.
```
spec/selector_spec.rb: RSpec/Capybara/SpecificMatcher has the wrong namespace - should be Capybara
spec/rspec/shared_spec_matchers.rb: RSpec/Capybara/VisibilityMatcher has the wrong namespace - should be Capybara
spec/rspec/shared_spec_matchers.rb: RSpec/Capybara/VisibilityMatcher has the wrong namespace - should be Capybara
Inspecting 259 files
:
```

Fix warnings when running RuboCop

---

lib/capybara/selenium/logger_suppressor.rb

Ruby 3 separated positional and keyword arguments, which changes the way we need to forward them. Just using `*` isn't enough, as exposed by #2666. We either need to use `...` or handle both positional and keyword. We opt for the latter approach here since it's compatible with the most Ruby versions.

selenium log suppression: forward both positional and keyword args

---

lib/capybara/selector/definition/table.rb
lib/capybara/selector/definition/table_row.rb
lib/capybara/spec/session/has_table_spec.rb

Fixes #2685
This adds a check to ensure that the `header_xp` exists before checking the that the position of the cell matches the position of the header. If `header_xp` does not exist then `header_xp.preceding_sibling.count.plus(1)` will still equal 1 and `XPath.position.equals` will be true for the first column.

table_row and with_rows ensure that the header matches locator for first column

---

lib/capybara/rack_test/node.rb
lib/capybara/spec/session/node_spec.rb
lib/capybara/spec/views/form.erb

Thanks for capybara!
I am attempting to update to the latest version, but am having some test failures from the change in https://github.com/teamcapybara/capybara/commit/6b05e5cb30e9807483c2641e9a60d89692bb0487 as I have forms where I set multiple inputs in the same form to values that end with `\n`.
I think ideally I'd be able to opt-out of the auto-submit behavior, but I'm unsure what the preferred path is. I'm happy to make updates to the branch here as well. Thanks again for all the work that goes into capybara!

Do not auto-submit forms if they have multiple inputs

---

lib/capybara/registrations/servers.rb

I had thought this might've been a "structural space", but it appears not.
The output for min threads has no space before the comma.
Just want to make them match.

Remove extra space in version string

---

lib/capybara/registrations/servers.rb
spec/server_spec.rb

Before, using capybara on a project with rack 3 would emit the following warning:
> Rack::Handler is deprecated and replaced by Rackup::Handler
This was because the capybara server registration code for `:puma` was referencing the deprecated `Rack::Handler::Puma` constant.
Fix by detecting and preferring the `Rackup::Handler::Puma` constant, if present.
Fixes #2705

Fix deprecation warning when booting puma using rack 3

---

lib/capybara/rack_test/browser.rb

This violates the Rack SPEC and causes failures if the application you are testing uses Rack::Lint.
I could not find any existing specs that test the environment that capybara passes to rack-test, so this does not include specs.

Do not pass an explicit nil CONTENT_TYPE in the rack_test browser

---

lib/capybara/minitest.rb
lib/capybara/minitest/spec.rb
lib/capybara/node/matchers.rb
lib/capybara/rspec/matchers.rb
lib/capybara/session.rb
lib/capybara/spec/session/has_element_spec.rb
spec/minitest_spec.rb
spec/rspec/shared_spec_matchers.rb

While other, more specific, selectors and matches exist, it's very common for test suites to fall back to CSS's support for attribute matching.
For example, it's common for suites to find `<img>` elements by their `[src]` value through concatenating a CSS Selector string:
```ruby
expect(page).to have_css("img[src=#{image_path}]")
```
Sometimes, including double quotes into the String isn't necessary, but when it is, it leads to escaping, combined `'` and `"` usage, alternative syntaxes like `%{...}`, or calls to `String#inspect`:
```ruby
expect(page).to have_css("img[src=\"#{image_path}\"]")
expect(page).to have_css('img[src="#{image_path}"]')
expect(page).to have_css(%{img[src="#{image_path}"]})
expect(page).to have_css("img[src=#{image_path.inspect}]")
```
The `:element` selector …

Introduce `Node#has_element?`

---

lib/capybara/queries/selector_query.rb
lib/capybara/spec/session/find_spec.rb
lib/capybara/spec/session/node_wrapper_spec.rb

While using some custom selectors, I was annoyed by the error description when not using a locator as the message would include "nil" in it which seems a bit off.
For instance:
```
expect(page).to have_list_item(text: 'Admin User', position: 2) }
=> expected to find visible list_item nil with text "Admin User" but there were no matches. Also found [...] which matched the selector but not all filters.
```
This PR removes the `locator.inspect` from the description if `locator` is `nil`.

Remove locator from query description if nil

---

lib/capybara/registrations/drivers.rb

Earlier this year (2023), Chrome released Chrome for Testing, a new Chrome flavor that targets testing and automation use cases. This flavor has been accessible using the `--headless=new` option since Chrome 109, released on January 1, 2023. This new mode supports the full browser capabilities, including running extensions.
The default headless mode is still pointed to `--headless=old` for now, but it's planned to be changed to `new` over time.
This commit explicitly chooses the `new` headless mode, that uses Chrome for Testing.
Solves #2725

Use the new headless Chrome on the pre-registered driver

---

README.md

There are two rspec-rails documentation links in the `README` to the old relishapp documentation. I've replaced them with updated links to the new docs:
- https://relishapp.com/rspec/rspec-rails/v/4-0/docs/directory-structure to https://rspec.info/features/6-0/rspec-rails/directory-structure/
- https://relishapp.com/rspec/rspec-rails/docs/system-specs/system-spec#system-specs-driven-by-selenium-chrome-headless to https://rspec.info/features/6-0/rspec-rails/system-specs/system-specs
This also changes the doc links from v4 to v6 - not sure if that's acceptable?

Update rspec-rails documentation links in README

---

History.md
lib/capybara/result.rb
spec/result_spec.rb

Delegate to `Capybara::Result#full_results` in order to support Ruby's multiple assignment:
```ruby
node = Capybara.string <<~HTML
<ul>
<li>Alpha</li>
<li>Beta</li>
<li>Gamma</li>
<li>Delta</li>
</ul>
HTML
first, *rest, last = node.all("//li", minimum: 0)
expect(first).to have_text "Alpha"
expect(rest.first).to have_text "Beta"
expect(rest.last).to have_text "Gamma"
expect(last).to have_text "Delta"
```

Delegate `Capybara::Result#to_ary`

---

README.md
lib/capybara/selector.rb

The [Capybara::Selector][] documentation highlights the wealth of capabilities that Capybara provides out of the box with its built-in selectors.
While they're powerful, they're often misunderstood. This adds a dedicated heading to the README to elaborate more on how they work across the entire system. The main aim is to highlight how most methods support the trio of Selector arguments: name, locator, and filters.
[Capybara::Selector]: https://rubydoc.info/github/teamcapybara/capybara/master/Capybara/Selector

Expand on `Capybara::Selector` documentation

---

.github/dependabot.yml

This PR adds a configuration to tell Dependabot to update the versions used for some well-known GitHub Actions, such as `checkout`, in order to avoid deprecation warnings when those get too old. [Documentation](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot)

chore(CI): Tell dependabot to update GH Actions

---

lib/capybara/selector.rb

The id name specified in find is invalid.
content => field

Fix a document typo

---

lib/capybara/selector/definition/frame.rb
lib/capybara/selector/definition/label.rb
lib/capybara/selector/definition/table.rb

I found a few places where passing a symbol as a test ID doesn't work as expected. All of the other selector types support symbols as for test ID selectors.

Consistently support passing a symbol as a test_id

---

README.md
lib/capybara/selector.rb

The multi-line Strings in the Selector code samples are breaking YARD's support for Ruby syntax highlighting.
This commit resolves those issues by using more multi-line `#` comment characters.

Resolve syntax highlighting issues in Ruby examples

---

lib/capybara/selector/definition/table_row.rb
lib/capybara/spec/session/has_table_spec.rb

The `:table_row` selector supports both `Hash` and `Array` arguments. Many other selectors support omitting the `locator` argument, so this commit adds support for omitting the `locator` from `:table_row`.
This can be useful when grabbing all rows and making assertions about sort order:
```ruby
table = find :table, "My Table"
header, first, second, third = table.all :table_row
header.assert_text "Header"
first.assert_text "First row"
second.assert_text "Second row"
third.assert_text "Third row"
```

Support `:table_row` without locator argument

---

lib/capybara/spec/test_app.rb

Rack::Protection 4.1.0 has introduced new `Rack::Protection::HostAuthorization` [[1]]. This makes `www.example.com` host to be rejected. The easiest solution is to disable this check for the TestApp.
The `permitted_hosts` could be more elaborated, e.g. `set :host_authorization, { permitted_hosts: [".example.com", "127.0.0.1"] }` also helped. While it seems weird to me, the `127.0.0.1` needs to be included to pass the test in [spec/session/current_url_spec.rb](https://github.com/teamcapybara/capybara/blob/master/lib/capybara/spec/session/current_url_spec.rb)  🤷
I have also tested this PR against Sinatra / Rack::Protection 4.0.1 and the "unknown" `:host_authorization` does not seem to cause any troubles.
This should help address issues observed in #2811
[1]: …

Disable `Rack::Protection::HostAuthorization`

---

lib/capybara/selenium/driver.rb
lib/capybara/selenium/driver_specializations/chrome_driver.rb

Fixes https://github.com/teamcapybara/capybara/issues/2793
Chromedriver no longer always sends the current window handle as the first item in the `get_window_handles` response, so you need to check `window_handle` if you want to figure out which one is current.

Handle chromedriver sending devtools window as a distinct window handle

---

lib/capybara/spec/session/has_button_spec.rb

Tests for the `exact: true` option already exist for `have_text` and `have_title`, but similar tests were missing for have_button and have_no_button, which also support the exact option.
This PR adds tests for the `exact: true/false` option in both have_button and have_no_button. These tests ensure that the button matching behavior works correctly when using the exact option to check for exact text matches.

Add tests for exact: true/false option in have_button and have_no_button
