teamcapybara/capybara

- lib/capybara/node/element.rb
- lib/capybara/node/finders.rb
- lib/capybara/result.rb
- lib/capybara/selenium/driver.rb
> Fix API doc references to non-existent Capybara::Element

- README.md
Clean up formatting of README note about Rails 4.0/4.1 test environment thread safety.
> Clean up formatting of README note

- lib/capybara.rb
- lib/capybara/server.rb
- lib/capybara/spec/session/reset_session_spec.rb
- lib/capybara/spec/test_app.rb
> Allow configuring the errors which will be raised by the server

- lib/capybara/rack_test/browser.rb
- lib/capybara/spec/session/click_link_spec.rb
- lib/capybara/spec/views/with_html.erb
Fix for issue #1491 while using the racktest driver
> Javascript void

- README.md
- lib/capybara.rb
- lib/capybara/node/base.rb
- lib/capybara/node/document_matchers.rb
- lib/capybara/node/finders.rb
- lib/capybara/node/matchers.rb
- lib/capybara/queries/base_query.rb
- lib/capybara/rspec/matchers.rb
- lib/capybara/selenium/driver.rb
- lib/capybara/session.rb
- lib/capybara/spec/session/window/become_closed_spec.rb
- lib/capybara/spec/session/window/window_opened_by_spec.rb
- lib/capybara/spec/spec_helper.rb
- spec/capybara_spec.rb
- spec/dsl_spec.rb
Implementation of the request/discussion in Issue #1442
> rename default_wait_time to default_max_wait_time - Issue #1442

- lib/capybara/rack_test/form.rb
The explicit dependency on this Rack method breaks when upgrading to Rack 2 because Rack::Utils.normalize_params has been moved since this commit https://github.com/rack/rack/commit/7e7a3890449b5cf5b86929c79373506e5f1909fb
There's [a very similar version in Rack::QueryParser](https://github.com/rack/rack/blob/master/lib/rack/query_parser.rb#L78), but it has
the downside of trying to make a hash of Rack::QueryParser instances
instead of a hash of hashes.
> Rack 2: Inline the version of normalize_params that used to exist in Rack::Utils

- lib/capybara/selenium/node.rb
- spec/selenium_spec.rb
This is a WIP on more fill_options for node#set with the selenium driver
> more fill_options for selenium node#set

- lib/capybara/rspec/features.rb
- spec/rspec/features_spec.rb
- spec/rspec/scenarios_spec.rb
Introducing `xfeature`, `ffeature` and `fscenario`
> Add more RSpec aliases

- lib/capybara/queries/selector_query.rb
- lib/capybara/spec/session/has_selector_spec.rb
Warn when unused parameters are passed to SelectorQuery
> Warn when extra parameters passed to SelectorQuery

- lib/capybara/node/actions.rb
- lib/capybara/node/finders.rb
- lib/capybara/spec/session/click_link_spec.rb
- lib/capybara/spec/session/find_button_spec.rb
- lib/capybara/spec/session/find_field_spec.rb
- lib/capybara/spec/session/find_link_spec.rb
Make locator optional in finders and actions where it makes potential sense
> Optional locator

- lib/capybara/queries/selector_query.rb
- lib/capybara/selector.rb
- lib/capybara/selector/filter_set.rb
- lib/capybara/spec/session/find_spec.rb
Implementation of reusable sets of filters for selectors - This came out of Issue #1463 .
I'm not convinced this is hugely useful, although for projects that build a large number of custom selectors it may be. Thinking about it.
> Filter sets

- History.md
- lib/capybara/node/matchers.rb
- lib/capybara/spec/session/element/matches_selector_spec.rb
Add Node#matches_xpath?/matches_css? sugar for matches_selector?
> Add matches_xpath? and matches_css? on top of matches_selector?

- lib/capybara.rb
- lib/capybara/result.rb
- lib/capybara/selector/selector.rb
- lib/capybara/session.rb
Here's a fix for some Ruby warnings.
> Ruby warnings ⚠️

- lib/capybara/node/actions.rb
- lib/capybara/spec/session/check_spec.rb
Potential alternate to PR#1787
> speedup label clicking behavior

- README.md
Hope this will save few minutes for other developers. Thanks.
> Add docs about Capybara.save_path and #save_screenshot

- lib/capybara/node/matchers.rb
- lib/capybara/session.rb
- lib/capybara/spec/session/assert_all_of_selectors_spec.rb
Add assertions to match all/none of a group locators applied to a specific selector type.
> Add assert_all_of_selectors and assert_none_of_selectors

- History.md
This is a port of 8ba2fa825f6e28cdf7233679b0a145cd09ffc2c3.
If not planning to commit to the master branch, please close it. Thanks!
> add history of v2.12.1 [ci skip]

- lib/capybara/minitest.rb
```refute_chceked_field -> refute_checked_field```
> Typo in doc comment

- lib/capybara/selector.rb
- lib/capybara/spec/session/has_select_spec.rb
- lib/capybara/spec/views/form.erb
Add :with_selected filter connected with [this](https://github.com/teamcapybara/capybara/issues/1865) issue.
> Add :with_selected filter to :select selector

- History.md
- lib/capybara.rb
- lib/capybara/session.rb
- lib/capybara/spec/session/visit_spec.rb
> Don't overwrite port when no server or always include port is false

- README.md
I noticed a small issue on README.md, and thought of fixing it.
> Correct typo on README

- lib/capybara/selenium/driver.rb
- lib/capybara/spec/session/reset_session_spec.rb
This should fix issue #1984 for selenium.  Poltergeist/capybara-webkit/etc will need updates.  A different option would be to move this into Session#reset!
> Driver reset! should close all but 1 window

- .gitattributes
- README.md
- Rakefile
- appveyor.yml
- capybara.gemspec
- lib/capybara/selenium/driver.rb
- lib/capybara/spec/session/attach_file_spec.rb
- lib/capybara/spec/session/refresh_spec.rb
- lib/capybara/spec/session/save_screenshot_spec.rb
- lib/capybara/spec/spec_helper.rb
- spec/selenium_spec_chrome.rb
- spec/selenium_spec_edge.rb
- spec/selenium_spec_ie.rb
- spec/selenium_spec_marionette.rb
- spec/server_spec.rb
- spec/shared_selenium_session.rb
- spec/spec_helper.rb
> Windows CI

- lib/capybara.rb
A similar PR was just merged into Rails: https://github.com/rails/rails/pull/32488
> Only disable headless chrome gpu on Windows

- .travis.yml
- Rakefile
- docker-compose.yml
- lib/capybara/selenium/driver.rb
- lib/capybara/selenium/node.rb
- spec/selenium_spec_chrome_remote.rb
- spec/shared_selenium_session.rb
This is a WIP PR to start running selenium with the `remote` browser type on CI. This will most likely cause some breakage; which I will address before this is merged :grinning:
> [WIP] Run Chrome remote configuration in CI

- .rubocop.yml
- .travis.yml
- appveyor.yml
- capybara.gemspec
- lib/capybara/driver/base.rb
- lib/capybara/node/actions.rb
- lib/capybara/node/matchers.rb
- lib/capybara/queries/ancestor_query.rb
- lib/capybara/queries/base_query.rb
- lib/capybara/queries/current_path_query.rb
- lib/capybara/queries/selector_query.rb
- lib/capybara/queries/sibling_query.rb
- lib/capybara/queries/text_query.rb
- lib/capybara/result.rb
- lib/capybara/selector.rb
- lib/capybara/selector/css.rb
- lib/capybara/selector/selector.rb
- lib/capybara/selenium/driver.rb
- lib/capybara/server.rb
- lib/capybara/session.rb
- lib/capybara/spec/spec_helper.rb
- lib/capybara/version.rb
Ruby 2.2 went EOL on 2018-03-31 - Consider moving the next minor release (v 3.2) to only supporting Ruby 2.3+
> Require minimum of Ruby 2.3.0

- lib/capybara/queries/selector_query.rb
- lib/capybara/selector/css.rb
- spec/css_splitter_spec.rb
This implements a very rudimentary parser attempting to split the CSS expression correctly on commas.  Still needs a lot of testing.
> WIP 3.2 css parser

- lib/capybara/selenium/node.rb
- lib/capybara/spec/session/node_spec.rb
- lib/capybara/spec/views/form.erb
- spec/shared_selenium_session.rb
> fieldset elements should correctly respond to `disabled?`

- lib/capybara.rb
- lib/capybara/config.rb
- lib/capybara/spec/spec_helper.rb
- spec/basic_node_spec.rb
> Make gumbo use configurable

- README.md
corrected a small typo in the readme
> typo in the readme

- lib/capybara.rb
- lib/capybara/spec/test_app.rb
> Raise all server errors by default, including Exception

- lib/capybara/selector.rb
- lib/capybara/spec/session/find_spec.rb
- lib/capybara/spec/views/with_html.erb
> Fix :link selector test_id issue caused by operator precedence - Issue #2166

- lib/capybara/server/animation_disabler.rb
Resolves https://github.com/teamcapybara/capybara/issues/2221
Very hard to add test cases for due to https://github.com/SeleniumHQ/selenium/issues/2517 .
> Disable animations on pseudoelement content as well as regular elements

- lib/capybara/selector/css.rb
- spec/result_spec.rb
> Fix miscellaneous new Rubocop issues

- lib/capybara/selector/definition/checkbox.rb
- lib/capybara/selector/definition/radio_button.rb
Should be `inspect` instead of `inspec`.
> Fixed typo

- .rubocop.yml
- History.md
- lib/capybara/selector/definition/table.rb
- lib/capybara/spec/session/has_table_spec.rb
Verify cell is present as well as the position being valid
> Fix issue #2287

- lib/capybara/selector.rb
- lib/capybara/selector/definition/select.rb
- lib/capybara/spec/session/has_select_spec.rb
> Implement enabled_options and disabled_options filters for select selector

- History.md
- lib/capybara/node/element.rb
- lib/capybara/selenium/driver.rb
- lib/capybara/selenium/node.rb
- lib/capybara/selenium/nodes/chrome_node.rb
- lib/capybara/selenium/nodes/firefox_node.rb
- lib/capybara/selenium/patches/action_pauser.rb
- lib/capybara/spec/public/test.js
- lib/capybara/spec/session/node_spec.rb
- spec/selenium_spec_chrome.rb
- spec/selenium_spec_chrome_remote.rb
> Implement click delay

- .rubocop.yml
- .travis.yml
- History.md
- README.md
- capybara.gemspec
- features/step_definitions/capybara_steps.rb
- lib/capybara/node/actions.rb
- lib/capybara/node/matchers.rb
- lib/capybara/queries/style_query.rb
- lib/capybara/selector/definition.rb
- lib/capybara/selector/definition/table.rb
- lib/capybara/selenium/driver_specializations/chrome_driver.rb
- lib/capybara/selenium/driver_specializations/edge_driver.rb
- lib/capybara/selenium/nodes/firefox_node.rb
- lib/capybara/selenium/patches/logs.rb
- lib/capybara/spec/test_app.rb
- spec/server_spec.rb
Ruby 2.4 goes EOL on 3/31 - drop support.
> Ruby 2 4 EOL

- lib/capybara/result.rb
- spec/result_spec.rb
> Stop using lazy enumeration with any version of JRuby

- lib/capybara/queries/text_query.rb
Introduced in https://github.com/tiramizoo/capybara/commit/b81aed55bb3c6ed6be37b3a2388ddf9a3d098119
> Fixed string interpolation

- lib/capybara/minitest.rb
- lib/capybara/queries/current_path_query.rb
- lib/capybara/rack_test/form.rb
- lib/capybara/rspec/matchers.rb
- lib/capybara/rspec/matchers/have_current_path.rb
- lib/capybara/session/matchers.rb
- lib/capybara/spec/session/has_current_path_spec.rb
- spec/minitest_spec.rb
Add support for optional filter block to current path assertions/matchers
> Current path filter block

- lib/capybara/window.rb
Just removes an unused method.
> Window#raise_unless_current is no longer used

- lib/capybara/selenium/extensions/find.rb
> Protect against optimization returning nil

- lib/capybara/session.rb
> Add evaluate_async_script to Capybara::Session::DSL_METHODS

- README.md
I explained with some more details to the `!has_xpath/has_no_xpath` differences. 
I tried to use simple english as much as possible for everyone to understand
thank you @freesteph and @skelz0r for the explanations 🙇
> clarify AJAX wait behaviour example in README

- lib/capybara/server/animation_disabler.rb
Animation Disabler is installed as a rack middleware - it will be
instantiated once and the call method will be called by multiple
requests.
The code was using instance variables on the middleware for information
about individual requests. When multiple requests were made at the same
time, the subsequent request would replace the status/headers/body of
the original request, causing the original request to return the
response of the subsequent request.
> Make animation disabler threadsafe

- README.md
While going through the readme file, I noticed a few grammatical errors, so I used Grammarly to double-check the content. I made a few minor changes to the readme file based on Grammarly's suggestions.
> Minor grammatical changes

- lib/capybara/selenium/driver_specializations/firefox_driver.rb
- lib/capybara/selenium/node.rb
- lib/capybara/selenium/patches/action_pauser.rb
- spec/selenium_spec_chrome_remote.rb
- spec/spec_helper.rb
> fix: strict version comparison method
